### ISSUE TITLE
Docker build isssue

### ISSUE THREAD

**Issue by jkuruzovich** [ucbds-infra/otter-grader#107]
There is a current issue with one of the dependencies nb2pdf that causes the build to error out. 

There is temporary solution [here](https://github.com/ucbds-infra/nb2pdf/issues/5).   

If you change the build of the docker file to the line below it builds ok.

```
RUN pip3 install git+https://github.com/eldridgejm/nb2pdf
```
Just putting the solution here in case anyone else runs into it.

**Comment by leestott** [comment]
@chrispyles 

otter-grader install error which is causing Docker container to fail deployment 

Collecting otter-grader
  Using cached otter_grader-0.4.7-py3-none-any.whl (29 kB)
Collecting nb2pdf
  Using cached nb2pdf-0.6.1-py3-none-any.whl (7.9 kB)
Collecting tornado==5.1.1
  Using cached tornado-5.1.1.tar.gz (516 kB)
Collecting codecov
  Using cached codecov-2.1.8-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: nbformat in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from nb2pdf->otter-grader) (4.4.0)
ERROR: Could not find a version that satisfies the requirement nbpdfexport==0.2.2 (from nb2pdf->otter-grader) (from versions: 0.1, 0.2, 0.2.1)
ERROR: No matching distribution found for nbpdfexport==0.2.2 (from nb2pdf->otter-grader)

issue on Nb2pdf repo - 
https://github.com/ucbds-infra/nb2pdf/issues/5
issue on Foundation of Data Science CodeSpaces environment repo 
https://github.com/MicrosoftDocs/inferentialthinking/issues/8

**Comment by chrispyles** [comment]
Try reinstalling nb2pdf (should install as 0.6.2). This version should have the dependency issue resolve.

**Comment by chrispyles** [comment]
Going to close this as the issue appears resolved.
