### ISSUE TITLE
Public tests appears as hidden in Gradescope

### ISSUE THREAD

**Issue by taylorgibson** [ucbds-infra/otter-grader#112]
**Describe the bug**
When using the `otter assign` functionality a code test written using # TEST will appear as a hidden test when grading in Gradescope

**To Reproduce**
1. Create a test using a # TEST cell in a dev notebook
2. Create a student version using `otter assign`
3. Upload `autograder.zip` to Gradescope
4. Grade an assignment
5. Result of # TEST cell is classified as hidden in Gradescope

**Expected behavior**
I would expect such a test to be considered public, not hidden.

**Versions**
Python 3.8.5
Otter 1.0.0b10

**Additional context**
There were no hidden tests in the notebook.

![image](https://user-images.githubusercontent.com/5053805/91371316-a67a2480-e7de-11ea-9975-0680ecd7f750.png)

![image](https://user-images.githubusercontent.com/5053805/91371260-7e8ac100-e7de-11ea-8f75-8d482d471650.png)

**Comment by chrispyles** [comment]
So this actually looks like it's behaving correctly. This is a new format for the Gradescope results introduced in v1.0.0 and is outlined [here](https://otter-grader.readthedocs.io/en/latest/otter_generate/gs_results.html#instructor-view). Basically, there are 3 cases to consider:

- If a public test is failed, there is a single box for the test called `{test name} - Public` that displays the failed output of the test and is worth all of the points for that test.
- If all public tests pass but a hidden test fails, there are two boxes: one called `{test name} - Public` that shows `All tests passed!` and a second called `{test name} - Hidden` that shows the failed output of the test. The hidden test takes on all of the points for the test unless `--public-multiplier` (or `generate[public_multiplier]` in the case of Otter Assign) is passed to ensure that the scores add up correctly.
- If all tests pass, there are two boxes, `{test name} - Public` and `{test name} - Hidden`, that both show `All tests passed!`.

This is not the best solution but we couldn't think of one that met all of the requirements that we needed while displaying the information compactly. Please let me know if you can think of a better way.

**Comment by taylorgibson** [comment]
I see, thanks for the explanation. The language hidden and public confused me since it appears to be used in different contexts, but I understand the intended use now. Thans!
