### ISSUE TITLE
Trying to work on windows

### ISSUE THREAD

**Issue by jkuruzovich** [ucbds-infra/otter-grader#115]
I have TA who is trying to get this work on Windows.

When running  from the command line the otter command doesn't work. 

(1) Any advice on getting this to work on windows?

(2) Alternately would it be easy to import the module and run the command directly as I'm already executing from Python?

Thanks in advance 
Jason

**Comment by chrispyles** [comment]
As noted in the [documentation](https://otter-grader.readthedocs.io/en/latest/#installation), if you're running Otter on Windows the command line `otter` tool won't work for you. Instead, run otter as a module:

```
python3 -m otter
```

All commands, arguments, etc. are the same.

**Comment by ttimbers** [comment]
A possibly related issue is coming up from students working on Windows when running `check.grade()` (otter assigments created as Python Jupyter notebooks)... The error there is shared below and we are trying a similar fix, but again wondering if it could be worthwhile specifying encoding='utf-8' in the open functions in this package to avoid that in future?

(sorry for the screenshot, but this is how the student sent it, I think the most critical part of the error is what I paste in text below)

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4398: character maps to <undefined>
```

![image (1)](https://user-images.githubusercontent.com/6865016/132555623-0fd1c350-a036-49b0-99ab-829afb38248e.png)
![image (2)](https://user-images.githubusercontent.com/6865016/132555641-1d073037-449e-44ae-9cf3-c480d88004c1.png)
