### ISSUE TITLE
Customizing grading with multiple hidden tests per question

### ISSUE THREAD

**Issue by da03** [ucbds-infra/otter-grader#121]
**Is your feature request related to a problem? Please describe.**
With multiple hidden tests per question, if a single hidden test failed, the entire hidden score of this question becomes 0. 

**Describe the solution you'd like**
Can you provide a feature to allow for assigning scores proportional to the number of hidden tests passed?

**Describe alternatives you've considered**
I considered breaking up the question with multiple hidden tests into multiple questions each with a single hidden test, but that's not natural semantically.

**Additional context**
We're using this for a class at Harvard, which is going on right now...

**Comment by chrispyles** [comment]
One of the changes coming up with the forthcoming v2.0.0 will change the granularity at which test results are reported to test-case-by-test-case rather than by test file, which effectively implements this change.

**Comment by da03** [comment]
Sounds great. Looking forward to the new version!

**Comment by chrispyles** [comment]
Beta version of v2 is out now! We'll be officially releasing soon (in the next week or two). Closing this thread now, but reopen if upgrading after the official release doesn't fix this issue.
