### ISSUE TITLE
Flag for alternative to ellipsis in solution replacement

### ISSUE THREAD

**Issue by afranks86** [ucbds-infra/otter-grader#122]
**Is your feature request related to a problem? Please describe.**
I'm trying out otter with Rmarkdown.  By default solutions are replaced with `...`, which in R has a very different meaning than it does in Python.  As a consequence, you can't knit Rmarkdown until ellipses are replaced.  I want students to be able to knittable immediately so that they can continuously knit as the work through the solutions.

**Describe the solution you'd like**
A flag in `otter assign` for specifying the replacement text, e.g. in R this could be `NULL` instead of `...`.  

**Describe alternatives you've considered**
I can manually search and replace `...` with `NULL` after running `otter assign`.  Alternatively I can set `eval=FALSE` globally so that no code chunks are evaluated.  That should enable you to knit the file without errors.

**Additional context**

**Comment by chrispyles** [comment]
This is a pretty simple fix... although I think replacing with `NULL` might gives students the wrong idea. What about, e.g., a string like `"YOUR CODE HERE"` or some other value indicating that the statement needs to be replaced? Or a line with `NULL # YOUR CODE HERE` as an indicator to students?

**Comment by afranks86** [comment]
I agree. For inline prompts I like `NULL # YOUR CODE HERE` and for multi-line solution removal just
```
## YOUR CODE HERE
```

Even `"..."` would work better in R than a regular ellipsis but still matches the python.  But I think this also might not send the correct message.

**Comment by afranks86** [comment]
I have another thought which is specific to RMarkdown that I think is the best case solution. I assume this is much more difficult to implement, however:

For any code chunks with solution removal, in addition to adding the placeholder text, set the chunk option [`eval=FALSE`](https://yihui.org/knitr/options/#code-evaluation).  This way, R would not run any code without students explicitly setting `eval=TRUE`, after attempting a solution.  With `eval=FALSE` you could still knit the assignment with unfinished / unattempted solutions, which would be useful for releasing a pdf of the assignment template, for example.

**Comment by chrispyles** [comment]
While this is do-able, I am hesitant for the same reason as just indicating `NULL`. I don't think students will realize they need to change this when the knit and so their knitted document won't include the output of those cells. I think that `NULL # YOUR CODE HERE` is the best option.

**Comment by chrispyles** [comment]
Opened #124 and released v1.1.3 which implements this change.

**Comment by afeld** [comment]
Came to open a similar issue.

> I don't think students will realize they need to change this

I think this is the same for `...` — thinking `# YOUR CODE HERE` would be much more explicit. Using Python in my case.) Happy to open a new issue if that's better.

**Comment by chrispyles** [comment]
@afeld yes, please open a new issue for this feature request.
