### ISSUE TITLE
Indexing error for hidden test when running autograder file in student environment

### ISSUE THREAD

**Issue by afranks86** [ucbds-infra/otter-grader#128]
**Describe the bug**
In Rmarkdown, I'd like to test the solution file (from the autograder folder) in the student environment.  When there is only a hidden test for a question, in the student tests cases is an empty vector, e.g.  `cases: []`.  However the autograder solution file still includes an `ottr::check` cell for that question leading to the following error:

`Error in suite_results[[1]] : subscript out of bounds`

This can be easily filxed by removing `ottr::check` from the autograder file but if there are many instances of this issue, it might be a pain.  It's cleaner if a test with no cases automatically passes without error.

**To Reproduce**
1. Create a question with one hidden test and no visible tests.  
2. Run `otter assign`
3. Move the Rmd from the `autograder` folder into the `student` folder and run.

**Expected behavior**
autograder Rmd file runs without error when evaluated in the `student` folder

**Versions**
Please provide your Python and Otter versions. The Otter can be obtained using `from otter import __version__`

**Additional context**

**Comment by chrispyles** [comment]
@afranks86 I've just made a pre-release version of ottr 0.0.2. Can you please install it and let me know if this error resolves itself?

```r
devtools::install_github("ucbds-infra/ottr@0.0.2")
```

**Comment by afranks86** [comment]
Great, yes the issue is resolved on ottr 0.0.2. Thanks!

**Comment by chrispyles** [comment]
Great! Will mark the release as official and close this issue.
