### ISSUE TITLE
 list the contents of requirements.txt directly in the metadata of the master notebook

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#129]
It would be very helpful if I could list the requirements (the contents of requirements.txt) directly in the metadata of the master notebook, so that the master notebook can be a self-contained file and can be moved around without the attached requirements.txt file. This would be useful because Jupyter notebooks don't have great support for uploading/downloading multiple files, and the specific platform on which we're deploying doesn't have the zip command installed.

**Comment by chrispyles** [comment]
#132 implements this feature and it will be released with the forthcoming v2.0.0 first beta.

**Comment by champoll** [comment]
Thanks for implementing this, @chrispyles ! What syntax do I use to list the requirements? And could this be added to the documentation?

**Comment by chrispyles** [comment]
You can specify the requirements as a YAML list:

```
requirements:
     - pandas
     - numpy
     # etc.
```

I will look into adding this to the docs.

**Comment by chrispyles** [comment]
Docs updated with #406
