### ISSUE TITLE
otter-assign should clear the output of the student-facing notebook after generating it

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#137]
I wonder if it would be technically possible to modify otter-assign so it clears the output of the student-facing notebook after generating it. This would remove the numbers in brackets (e.g. [135] next to the cells where students are expected to add input. 

**Is your feature request related to a problem? Please describe.**
The student-facing notebook that otter-assign generates contains numbers that indicate that some cells have been run (e.g. [135] next to these cells). It turns out that these numbers are confusing some students who are new to Jupyter.

**Describe the solution you'd like**
otter-assign should clear the output of the student-facing notebook after generating it. 

**Describe alternatives you've considered**
The alternative consists in manually clearing the output of each student-facing notebook every time after otter-assign is run. 

**Additional context**
Manually clearing the output is time intensive because it can't be done from the command-line and can't be automated as far as I know.

**Comment by chrispyles** [comment]
Otter assign does currently clear the output, it just doesn't remove the run numbers. This is because the way parsing occurs is all done Pythonically without actually running the notebook.
