### ISSUE TITLE
public tests check results in output "All tests passed" even though hidden tests may have failed

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#138]
**Describe the bug**
When students run a check within their notebook, it outputs "All tests passed" whenever all public tests have been passed, even though hidden tests may not have been passed. This confuses students. 

**To Reproduce**
As a student, work on any problem in the notebook in a way that satisfies the relevant public tests, and run "grader.check()".

**Expected behavior**
The output should be configurable by the instructor, and the default output should be "All public tests passed" rather than "All tests passed".

**Versions**
Python version: 3.8.5
Otter-Grader version: 1.1.3

**Additional context**

In general, I prefer not to tell students to ignore the output of otter-grader because I want them to be able to rely on it and to pay attention to it. 

Sample email by a student:

"I was just submitting my assignment on my gradebook and I noticed I got a 51/70 on the first jupyter assignment. I'm just a little confused because when I submitted the assignment I had like the "all tests passed" thing but it says I was missing stuff in my assignment. Is there something I'm missing in the assignment? What should I do next time to avoid this? "

**Comment by chrispyles** [comment]
Otter's client-side package is agnostic of the visibility of the tests, and this verbiage was chosen because from the client's perspective the student _has_ passed all available tests. There are also instances in which assignments have no hidden tests, and the output shouldn't hint that there may be nonexistent tests.

**Comment by champoll** [comment]
It sounds like different instructors have different needs -- in my case, I always assign hidden tests and I tell the students about them, so the message "All tests passed" is untruthful and confusing from the student's point of view.  Since an instructor who doesn't use hidden tests would not want to issue the message "All public tests passed", it seems the best solution is to provide a way for the instructor to customize the message. Could this be implemented?

**Comment by chrispyles** [comment]
Unfortunately, this seemingly-simple change would require a significant overhaul of much of Otter. I don't think that's currently feasible, but we'll keep this in mind going forward.
