### ISSUE TITLE
Otter grade don't recognize declared variable.

### ISSUE THREAD

**Issue by nnbaokhang** [ucbds-infra/otter-grader#141]
Otter grade doesn't pickup predefined variables when run   *.ipynb files
Generic errors: NameError: name 'unemployment' is not defined, NameError: name 'boston_under_10' is not defined. 
There are many more but I just gonna give 2 examples here.

First example:
When I run otter grade, I get this following error. I already have unemployment variable before unemployment.select('Date', 'NEI', 'NEI-PTER').take(0) cell
---------------------------------------------------------------------
q1_1 > Suite 1 > Case 1

>>> unemployment.select('Date', 'NEI', 'NEI-PTER').take(0)
NameError: name 'unemployment' is not defined

# Error: expected
#     Date       | NEI     | NEI-PTER
#     1994-01-01 | 10.0974 | 11.172
# but got
#     Traceback (most recent call last):
#       ...
#     NameError: name 'unemployment' is not defined

Run only this test case with "python3 ok -q q1_1 --suite 1 --case 1"

Second example:

Running tests

---------------------------------------------------------------------
q4_3 > Suite 1 > Case 1

>>> boston_under_10 >= 0 and boston_under_10 <= 100
NameError: name 'boston_under_10' is not defined

# Error: expected
#     True
# but got
#     Traceback (most recent call last):
#       ...
#     NameError: name 'boston_under_10' is not defined

Run only this test case with "python3 ok -q q4_3 --suite 1 --case 1"

**Expected behavior**
It should not be any error since I already declare the variable before used it
**Versions**
Otter grader version 1.1.3
**Additional context**

**Comment by chrispyles** [comment]
Can you share the assignment you're running? Also this looks like the output from OkPy, not Otter. Which autograding technology are you using?

**Comment by nnbaokhang** [comment]
Sorry, I was able to grade student's notebooks with this setup
![image](https://user-images.githubusercontent.com/11141804/105106373-12517800-5a73-11eb-9043-8bc754f50d67.png)
