### ISSUE TITLE
Otter assign: add option to specify username and/or password on the command line

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#146]
**Is your feature request related to a problem? Please describe.**
Running otter assign on a gradescope-enabled notebook requires typing the gradescope.com username and password in manually a few seconds after starting the process. 

**Describe the solution you'd like**
There should be an argument to specify the username on the command line, and another argument to specify the password on the command line, e.g.:
otter assign -u username@gradescope.com -p iloveyou -r requirements.txt jupyter_notebook.ipynb dist/ 

**Describe alternatives you've considered**
An alternative would be to only require username and password to be specified once rather than on every run, similarly to what ssh does. 

**Additional context**
Typing in username and password manually can be quite tedious since rapid prototyping requires me to run otter dozens of times in a day. Also, I don't have my password memorized. Having both on the command line would allow me to rerun otter assign with just two keystrokes (uparrow + Enter).

**Comment by chrispyles** [comment]
Opened #175 with this fix
