### ISSUE TITLE
Gradescope is grading each question twice.

### ISSUE THREAD

**Issue by afranks86** [ucbds-infra/otter-grader#147]
**Describe your inquiry** 
I'm running otter on Gradescope for Rmarkdown files.

For the vast majority of student solutions, each question is graded twice (more weirdly, this does not seem to be happen 100% of the time). I can't figure out why this is happening, since this didn't happen in previous assignment and I think I'm following the same procedures.  It seems as if the second pass the assignment is graded based on the last state of the relevant variables, since I noticed there was a test based on a variable which was later overwritten.  On this particular script, the first time it was graded, it passed the test but the second time it didn't -- the second time it was clearly a value that overwrote the first.

I guess I'm wondering if you have any ideas about what might be going on, and also about the desired behavior: should the autograder results should be evaluated as the script is executed or is it saving relevant values of variables after the script finishes and then running tests? I think the former is better, and in this case it weirdly seems like both.

**Comment by chrispyles** [comment]
(Sorry for not responding to this sooner.)

I'm not really sure why this is happening. [This function](https://github.com/ucbds-infra/ottr/blob/master/R/ottr.r#L300) handles script execution in the autograder and it relies on each call to `ottr::check` to run `testthat` and collects the results in a list. There shouldn't be any double-execution going on, and tests are run at the corresponding points of execution that students run them.

Can you share a way to reproduce this behavior?
