### ISSUE TITLE
Slow down autograder execution by X minutes

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#148]
**Is your feature request related to a problem? Please describe.**
I'm using Gradescope and allowing unlimited submissions. The idea is that students are receiving very quick feedback from the autograder about whether their answers are correct, and can take this feedback into account as they keep working on the assignment. Some students are taking advantage of the fact that the autograder is very quick, by trying out every realistically possible answer for a given question until they hit the jackpot. 

**Describe the solution you'd like**
There should be a metadata option in the notebook that instructs the autograder to wait for a user-specified number of minutes before returning the results.  Ideally, this option should come with a way to disable this feature of the autograder, e.g. by whitelisting submissions that are submitted by certain students and/or that include a specific "cheat code".

**Describe alternatives you've considered**
An alternative would be to disable unlimited submissions on Gradescope. This would cause more problems than it would solve, because students can no longer take the autograder's feedback into account as they keep working on the assignment.

**Comment by chrispyles** [comment]
v2 (now in pre-release, official release upcoming) includes support for grading plugins and one of the built-in plugins is for rate-limiting submissions. Beta docs can be found [here](https://otter-grader.readthedocs.io/en/beta/) although the built-in plugins aren't yet documented.
