### ISSUE TITLE
Test failed when answers are correct and Questions are double graded

### ISSUE THREAD

**Issue by JiajingZ** [ucbds-infra/otter-grader#150]
**Describe the bug**
closely followed the otter sample at [https://github.com/ucbds-infra/ottr-sample](https://github.com/ucbds-infra/ottr-sample), the tests failed for "q2a" and "q3b" on the Gradescope while the answers in the tested submission Rmd. files are correct and tests can be passed when running locally in R. In addition, all questions are double graded. See pictures below:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/44931801/99329883-027ba480-2834-11eb-83a0-0219c5623f16.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/44931801/99329901-0f989380-2834-11eb-86d2-9817969e4594.png">
<img width="111" alt="image" src="https://user-images.githubusercontent.com/44931801/99329919-1e7f4600-2834-11eb-80bb-eb07a23e011f.png">

**To Reproduce**
Follow exactly the steps at [https://github.com/ucbds-infra/ottr-sample](https://github.com/ucbds-infra/ottr-sample) using files in folder "hw01"

**Expected behavior**
all tests should pass for the tested submission .Rmd file, and all questions are graded only once.

**Version**
Python version: 3.7.3
Otter-Grader version: 1.1.5

**Comment by chrispyles** [comment]
v0.1.0 of ottr fixes this issue. Upgrading locally/reuploading a configuration zip file to Gradescope should install this new version.
