### ISSUE TITLE
Seed answer cells using R?

### ISSUE THREAD

**Issue by choldgraf** [ucbds-infra/otter-grader#151]
In a recent conversation we discussed how Otter Grader will re-seed each cell of a notebook if the instructors wish, in order to ensure reproducibility when grading work. Is it possible to do this with an R kernel?

**Comment by chrispyles** [comment]
Yes, easy to implement for Jupyter notebooks. Opened #173 with this feature

**Comment by chrispyles** [comment]
#173 merged, closing this issue.
