### ISSUE TITLE
'otter assign': PermissionError: The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by ajmueh** [ucbds-infra/otter-grader#152]
**Describe the bug**
Following the otter-grader [tutorial](https://otter-grader.readthedocs.io/en/latest/tutorial.html), I am receiving the following error when using otter assign with the 'assign-demo.ipynb' notebook on Windows 10:

![image](https://user-images.githubusercontent.com/21161072/99463143-f81be200-28e9-11eb-84c1-bf73568d200d.png)

**To Reproduce**
I'm following the steps on the otter grader tutorial. I extract the tutorial .zip file into a directory, cd into the assign folder, and run `py -m otter assign assign-demo.ipynb dist`

**Expected behavior**
The autograder zipfile should be successfully generated, and all tests passed. 

**Versions**
python 3.9.0 x64
otter-grader 1.1.5
Windows version 2004 build 19041

**Additional context**
The file given in the error sometimes changes, for example, at a previous point it was *PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tmp\\tests'*. The file has always been one of 'tmp', 'tmp\\tests', or 'tmp\\tests\\q1.py'

Also, I was previously having some issues with nbconvert when generating the solutions PDF, though appear to have solved that issue.

**Comment by chrispyles** [comment]
I believe this issue is because of the way in which zips are generated in the current stable release of Otter. Forthcoming v2.0.0.b0 should (hopefully) fix this. Keep an eye out for that release.

**Comment by chrispyles** [comment]
Closing this issue as v2.0.0 is now in pre-release. Please reopen if this issue persists after upgrading.
