### ISSUE TITLE
Allow spacing when ending solution

### ISSUE THREAD

**Issue by azpoliak** [ucbds-infra/otter-grader#153]
When I end a SOLUTION block with 
"# END SOLUTION ", these checks fail. 

https://github.com/ucbds-infra/otter-grader/blob/c7e93623ff4be861a4c3c95449f92e9711347b7a/otter/assign/solutions.py#L74-L81

Adding `.strip()` to the string before checking the end makes it more robust to instances where there are extra spaces or newline characters

**Comment by chrispyles** [comment]
Pushed a fix for this issue with 26de31c. It will be included in the next beta version of 2.0.0

**Comment by azpoliak** [comment]
Awesome! Thanks
