### ISSUE TITLE
accepting `.py` file submissions on gradescope 

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#176]
**Describe your inquiry** 
Does `otter generate autograder` work with accepting `.py` file submissions? If not, do you recommend editing autograder code, or asking students to convert their work to a notebook? Couldn’t find anything on this in the documentation. Asking for a colleague.

**Comment by chrispyles** [comment]
Currently it does not, but this should be a relatively simple addition. I'll keep this thread updated but anticipate it being a feature for v2.0.0

**Comment by chrispyles** [comment]
Opened #177
