### ISSUE TITLE
otter assign - `AssertionError: Requirements file requirements.txt not found"

### ISSUE THREAD

**Issue by cdbeon** [ucbds-infra/otter-grader#185]
**Describe the bug**
After updating otter-grader to v. 2.0.1, I attempted to create an assignment using `otter assign`. Unfortunately, while generating the autograder zipfile, otter-grader didn't recognize 'requirements.txt' and shows the AssertionError as listed in the title. The dist file was created, but without the autograder.zip as a result.

**To Reproduce**
This issue also persists when following the instructions for the hw01-assign.Rmd in the [ottr-sample github](https://github.com/ucbds-infra/ottr-sample).

Simply typing `otter assign hw01-assign.Rmd dist` (or any other Rmd file, for that matter) reproduces the error on my end.

**Expected behavior**
The autograder.zip file being generated in the autograder directory.

**Versions**
Python v.3.8.6
Otter v.2.0.1

**Additional context**
Currently attempting to generate the autograder.zip file for Gradescope. This is for an assignment in R, specifically on an Rmarkdown file. Not sure if there was something else I should update in addition to otter-grader in the terminal using pip. Thanks for helping out!

**Comment by chrispyles** [comment]
Opened #186 that fixes this issue and released v2.0.2
