### ISSUE TITLE
Make force-save optional by argument

### ISSUE THREAD

**Issue by taylorgibson** [ucbds-infra/otter-grader#208]
**Is your feature request related to a problem? Please describe.**
When using JupyterLab, an error message results from running Notebook.export due to force-save not being supported.

**Describe the solution you'd like**
Make force save an optional feature where instructors can specify manually whether or not to use it

**Additional context**
Running JupyterLab 3, Python 3.8, and Otter 2.1.1
![image](https://user-images.githubusercontent.com/5053805/106654910-b274ca00-6566-11eb-8207-68999ad120bc.png)

**Comment by chrispyles** [comment]
Added this change with f5df0e53ef26c0f74229d6d4363d8464812749fb

Should be released in v2.1.2 tonight.

**Comment by chrispyles** [comment]
v2.1.2 now officially released with #212. Closing this issue.
