### ISSUE TITLE
Error when going through Quickstart Tutorial

### ISSUE THREAD

**Issue by dfeehan** [ucbds-infra/otter-grader#209]
This project looks really cool - thanks for all of your work on it.

I'm getting an error when I go through the Quickstart Tutorial. I'm not sure if this is a bug, or if I'm doing something wrong.

I'm at the step where I'm running the grading in `tutorial/grade`. I actually have two problems here. First, I think I have to copy the autograder.zip file into the `grade` directory. No problem.

Then, the tutorial says to type

`otter grade -p ipynbs -j meta.json --pdfs html -v`

When I do that, I get the error "otter: error: unrecognized arguments: html".

OK, so when I leave out `html` and type

`otter grade -p ipynbs -j meta.json --pdfs -v`

things appear to go well for a while: Docker spins some stuff up, but eventually it crashes. I've posted the whole message at the bottom of this issue.

Finally, in case it's helpful, I am able to run

`otter grade -p ipynbs -j meta.json -v`

and things seem to work fine. At least, there are no errors and `final_grades.csv` appears in the directory.

Thanks again for your help!

Full error message / otter output:

❯ otter grade -p ipynbs -j meta.json --pdfs -v
Found JSON metadata...
Launching docker containers...
[+] Building 0.1s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                                        0.0s
 => => transferring dockerfile: 37B                                                                                         0.0s
 => [internal] load .dockerignore                                                                                           0.0s
 => => transferring context: 2B                                                                                             0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                   0.0s
 => [ 1/11] FROM docker.io/ucbdsinfra/otter-grader                                                                          0.0s
 => [internal] load build context                                                                                           0.0s
 => => transferring context: 84B                                                                                            0.0s
 => CACHED [ 2/11] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/li  0.0s
 => CACHED [ 3/11] RUN mkdir -p /autograder/source                                                                          0.0s
 => CACHED [ 4/11] ADD ./autograder.zip /tmp/autograder.zip                                                                 0.0s
 => CACHED [ 5/11] RUN unzip -d /autograder/source /tmp/autograder.zip                                                      0.0s
 => CACHED [ 6/11] RUN cp /autograder/source/run_autograder /autograder/run_autograder                                      0.0s
 => CACHED [ 7/11] RUN dos2unix /autograder/run_autograder /autograder/source/setup.sh                                      0.0s
 => CACHED [ 8/11] RUN chmod +x /autograder/run_autograder                                                                  0.0s
 => CACHED [ 9/11] RUN apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/*   0.0s
 => CACHED [10/11] RUN mkdir -p /autograder/submission                                                                      0.0s
 => CACHED [11/11] RUN mkdir -p /autograder/results                                                                         0.0s
 => exporting to image                                                                                                      0.0s
 => => exporting layers                                                                                                     0.0s
 => => writing image sha256:e73fa6353bc1a2feccbc3b184f8b93a358da7e8c1a705b65ef0dea4f0c80a9aa                                0.0s
 => => naming to docker.io/library/otter-grade:fd39632042794c6588f9cba78c6a2f5d                                             0.0s
Launched container 39fc2f40769f...
Launched container 2dff820a747c...
Grading notebooks in container 39fc2f40769f...
Launched container a18412227201...
Grading notebooks in container 2dff820a747c...
Launched container d379fd21bdbf...
Grading notebooks in container a18412227201...
Grading notebooks in container d379fd21bdbf...
Copying grades from container 39fc2f40769f...
Copying grades from container 2dff820a747c...
Copying grades from container a18412227201...
Stopping container 39fc2f40769f...
Copying grades from container d379fd21bdbf...
Stopping container 2dff820a747c...
Stopping container a18412227201...
Stopping container d379fd21bdbf...
Launched container 38c391d2110f...
Launched container db4f9bd929d4...
Grading notebooks in container 38c391d2110f...
Grading notebooks in container db4f9bd929d4...
Copying grades from container 38c391d2110f...
Copying grades from container db4f9bd929d4...
Stopping container 38c391d2110f...
Stopping container db4f9bd929d4...
Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/db4f9bd929d46d6ad8b739794b2b04d0c228204e91e24f7fb338243a89ad106f/archive?path=%2Fautograder%2Fsubmission%2Fdemo-passesAll.pdf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(run_otter())
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/runner.py", line 56, in run_otter
    args.func(**kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 104, in main
    pdfs=pdfs
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 106, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 106, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 194, in grade_assignments
    with get_container_file(container, f"/autograder/submission/{nb_name}.pdf") as pdf_file:
  File "/Users/dennis/opt/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/utils.py", line 62, in get_container_file
    bits, _ = container.get_archive(path)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/models/containers.py", line 262, in get_archive
    chunk_size, encode_stream)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/container.py", line 747, in get_archive
    self._raise_for_status(res)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("Could not find the file /autograder/submission/demo-passesAll.pdf in container db4f9bd929d46d6ad8b739794b2b04d0c228204e91e24f7fb338243a89ad106f")

**Comment by chrispyles** [comment]
Thanks for pointing this out! The tutorial was outdated but I've just finished updating it for Otter v2 with #211. Should be deployed to RTD shortly.

**Comment by dfeehan** [comment]
Great - thank you!
