### ISSUE TITLE
Otter Generate, 'test outside of a question'

### ISSUE THREAD

**Issue by jonluntzel** [ucbds-infra/otter-grader#214]
[Doc1.pdf](https://github.com/ucbds-infra/otter-grader/files/5921864/Doc1.pdf)

Hello, I am trying to get otter grader working on an example that is not the files being used from the tutorial so I created a dummy assignment with 3 questions to see if I could get it working. Attached in the PDF is the error I am running into, alongside the problem, the test (which should always pass), and the q1.py test file. 

My folder is setup as follows: within it, there's one 'assign' folder with the empty homework HW1.ipynb and homework with solutions and tests HW1-sol.ipynb. I also put both these files in the main folder. Then there's a 'grade' folder with student submissions in an ipynb folder, tests in a test folder, and a meta .json file.

Any help is appreciated

**Comment by chrispyles** [comment]
Did you add question metadata to the cell with the question text? In each Markdown cell containing a question, there should be a YAML-formatted metadata block like:

````
```
BEGIN QUESTION
name: q1
```
````

You can find more details about the Otter Assign notebook format [here](https://otter-grader.readthedocs.io/en/latest/otter_assign/python_notebook_format.html#autograded-questions).

**Comment by jonluntzel** [comment]
Hi Chris, thanks for the response. I added question metadata to question prompts and also deleted a cell between the prompt and test - not getting the error any more. However when I try to grade the assignments I am running into a new issue (fine to continue in this thread?) that complains about an unrecognized argument. Just trying to follow along the docs tutorial.

[Error encountered.pdf](https://github.com/ucbds-infra/otter-grader/files/5937879/Error.encountered.pdf)

I considered that the homework submissions themselves had issues - namely that I did not have a cell below each student's submission which ran 'grader.check("qx")', and running grader.export() at the end of each submission. But right now not sure how to debug this.

**Comment by chrispyles** [comment]
What version of otter are you running? You can find this information with `otter --version`

**Comment by jonluntzel** [comment]
Python version: 3.8.5
Otter-Grader version: 1.1.6

**Comment by chrispyles** [comment]
So the error you're getting is due to the fact that in v2 of Otter we updated the local grading workflow and the tutorial reflects that version. You should be able to upgrade to the most recent version (2.1.3) and have it work.

Closing this thread but please reopen if this doesn't work.
