### ISSUE TITLE
hidden tests aren't being displayed in output

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#224]
**Describe the bug**
Visible tests still show up on the right hand side, but hidden tests aresupposed to be displayed by the ascii printout. It looks like there are too many tests, though, so a bunch of them are getting ommitted. Only ellipses show up. See image below.

**Versions**
This is version '2.1.2'

**Additional context**

Here is a screengrab of what the student sees.

![image](https://user-images.githubusercontent.com/1740324/111663996-b5aad900-87e7-11eb-9b59-4f80332cf825.png)

Here is my `otter_config.json` file used in the `autograder.zip` build
```
{
   "show_stdout": true
}
```

**Comment by chrispyles** [comment]
Opened #225 that implements this fix. When that PR merges, I will release v2.1.5, and you can upgrade to that version.
