### ISSUE TITLE
Cannot try/except in tests

### ISSUE THREAD

**Issue by drjbarker** [ucbds-infra/otter-grader#228]
**Describe the bug**
Trying to use try/except in a hidden test causes the test to fail.

**To Reproduce**
Use try/except to attempt to catch an exception in a hidden test. Simple example:

```py
## HIDDEN TEST ##
# Test if function raises an exception
did_raise_exception = False
try:
    my_function()
except:
    did_raise_exception = True
print(did_raise_exception)
```

This executes fine in the jupyter notebook but fails in the testing framework.

One of two things happens:
- If `my_function()` raises an exception then this is not caught by except but raises immediately.
- If `my_function()` does not raise an exception then the test fails with unexpected EOF before reaching `except`.

**Expected behavior**
We should be able to test exception handling.

**Versions**
2.1.3

**Additional context**
I think the issue is that otter is evaluating the try block completely independently of the except block. There is a super hacky work around I can use which fixes it because (I think) all the code is on a single line:

```py
## HIDDEN TEST ##
# Test if function raises an exception
did_raise_exception = False
eval("try:\n  my_function()\nexcept:\n  did_raise_exception = True\n")
print(did_raise_exception)
```

**Comment by chrispyles** [comment]
I believe #230 fixes this issue. Can you try installing that version of Otter and let me know if it works?

```
pip install git+https://github.com/ucbds-infra/otter-grader.git@fix-228
```

**Comment by drjbarker** [comment]
Thanks for the quick work Chris. I can confirm this fixes the bug.

**Comment by chrispyles** [comment]
As an update, #230 is now in a stable release with version 2.1.6
