### ISSUE TITLE
Cannot access source code in tests

### ISSUE THREAD

**Issue by drjbarker** [ucbds-infra/otter-grader#229]
**Is your feature request related to a problem? Please describe.**
I'm aiming to walk an ast in a test but cannot access the source of the function for example using `inspect.getsource(some_function)`. This results in a `OSError: source code not available` presumably because we only have access to a compiled object within the grading framework (everything works fine in the original notebook).

In general there seems to be no way to access an ast of the solution cell even though it seems otter generates this to do the evaluation (based on this: https://otter-grader.readthedocs.io/en/latest/execution.html). 

**Describe the solution you'd like**
It would be useful to natively support `inspect.getsource` within the grader, maybe doing some 'injection' like with the random number seeding.

**Describe alternatives you've considered**
Possibly allowing access to the ast at least within a test .py file (even if not in the notebook format) as an advanced feature.

**Comment by chrispyles** [comment]
I believe #231 fixes this issue. Can you try installing that version of Otter and let me know if it works?

```
pip install git+https://github.com/ucbds-infra/otter-grader.git@fix-229
```

**Comment by drjbarker** [comment]
Doesn't seem to work. I've made a minimal example and tested. The issue seems to be that doctest can't find the source because it never exists in a file. Inside of doctest they play some tricks with the linecache to allow access to the source but only when debugging.

The two options I can think of at the moment are:
- Write the source to a temporary file and read this (not ideal)
- Play similar games with linecache (but I'm not 100% sure that will work)

I'm a bit busy at the moment (writing exams with otter!) but I might be able to take a look at a later date.

**Comment by chrispyles** [comment]
I think I've implemented a fix for this while refactoring out execution internals for v4. The fix uses `tempfile` to create a temporary file with the source before compiling, and I tested `inspect.getsource` in a test with this structure and it worked for me. This will be included as a feature in Otter v4.
