### ISSUE TITLE
Send email to student about Gradescope public tests

### ISSUE THREAD

**Issue by papajohn** [ucbds-infra/otter-grader#242]
**Is your feature request related to a problem? Please describe.**
If students upload the wrong zip to gradescope and then close the page, they won't know they've uploaded the wrong thing until after manual grading.

**Describe the solution you'd like**
When Gradescope runs public tests, couldn't Otter (running on Gradescope) just send an email to the submitter describing the result, so that the student doesn't have to wait on the Gradescope site for the public tests to complete?

**Comment by chrispyles** [comment]
This is a really interesting idea. Been tinkering around with this and I think I've got a passable implementation. This is what I'm thinking for the email contents:

```
Hello { student name },

Your submission for assignment { assignment title } submitted at { timestamp } received the following scores on public tests:

q1_1 results: All test cases passed!

q1_2 results: All test cases passed!

q2_1 results: All test cases passed!

q2_2 results: All test cases passed!

q2_3 results: All test cases passed!

q2_4 results: All test cases passed!

q2_5 results: All test cases passed!

q2_6 results: All test cases passed!

feedback results: All test cases passed!

If you have any questions or notice any issues, please contact your instructors.

---

This message was automatically generated by Otter-Grader.
```

Any thoughts/comments?

**Comment by chrispyles** [comment]
Screenshot of HTML version:

<img width="833" alt="Screen Shot 2021-06-03 at 10 35 56 PM" src="https://user-images.githubusercontent.com/40970945/120750988-18913f80-c4bc-11eb-9f30-c6e271653f3f.png">

**Comment by papajohn** [comment]
Looks great!

Fernando suggested adding a time stamp to the zip file name. (Not sure if
an issue was created about that yet.) If that’s the case, I’d include the
zip file name in the email if possible — should aid students in
troubleshooting when they submit the wrong version.

**Comment by chrispyles** [comment]
Yes, #243 was opened about that. However, since Gradescope automatically unzips the file, there's no way to recover the filename in the autograder, so I don't think that's doable.

**Comment by papajohn** [comment]
Maybe put the filename in the ZIP contents somewhere? (I know — now things
are getting complicated...)

**Comment by chrispyles** [comment]
OK I've opened #245 that implements a plugin for emailing students these results and also implements #243. This will be included in the next release of Otter, which will probably happen once that PR is merged.
