### ISSUE TITLE
Run tests locally against the exported zip archive

### ISSUE THREAD

**Issue by papajohn** [ucbds-infra/otter-grader#244]
**Is your feature request related to a problem? Please describe.**
In some cases, the exported zip will not pass public tests, even if all tests pass within the notebook. This can happen if a student:
- runs the export cell without first saving their notebook 
- has run cells out of order 
- has passed tests due to executed code that was deleted before export

**Describe the solution you'd like**
The export cell (at the bottom of an assignment notebook) should build the zip, then extract the code from the notebook in the zip, run the autograder tests against that extracted code (in a new Python process that isn't muddied by the notebook kernel state), and display the results of that test in the output of the export cell. The result should be equivalent to having Gradescope run public tests, but now they're run locally, so uploading to Gradescope isn't necessary to discover problems. 

The main advantage here is that problems detected by Gradescope public tests might be due to export issues (described above) or due to uploading the wrong file. This local run would be guaranteed to test the right zip, isolating issues. Also, students are more likely to notice a problem in the assignment notebook than on Gradescope, I think.

**Comment by chrispyles** [comment]
@nhudait any progress on this?

**Comment by chrispyles** [comment]
Implemented in #290. This feature will become part of the beta release of Otter v3, and will be part of a stable release when v3.0.0 is released.

**Comment by chrispyles** [comment]
This is what the report will look like:

<img width="726" alt="Screen Shot 2021-08-10 at 10 30 48 PM" src="https://user-images.githubusercontent.com/40970945/128974626-e7e7124c-3bf7-4489-bafa-154d09c90eae.png">
