### ISSUE TITLE
Docs redirect

### ISSUE THREAD

**Issue by papajohn** [ucbds-infra/otter-grader#27]
A lot of people have this link, because it used to hold the docs:

[1] https://github.com/ucbds-infra/otter-grader/blob/master/docs/index.md

But now it seems the docs are mostly here:

[2] https://nbviewer.jupyter.org/github/ucbds-infra/otter-grader/blob/master/demo/demo.ipynb

Could you add some links to [1] so that people who start there can find [2] and whatever else they need?

**Comment by chrispyles** [comment]
Demo notebook and old docs are outdated. We've just pushed new documentation to RTD that are up-to-date. This is where the docs will stay and be consistently updated. Sorry for the confusion!

https://otter-grader.readthedocs.io
