### ISSUE TITLE
how to reference data files when building autograder.zip

### ISSUE THREAD

**Issue by johnchaston** [ucbds-infra/otter-grader#291]
**Describe the bug**
The documentation instructs to run code such as the below to include a data file in the autograder.zip 

otter assign HW2.Rmd dist data/Amino-acid-codes2.csv
 
However, when I run it I get this:
 
usage: otter [-h] [--version] {assign,check,export,generate,grade,run} ...
otter: error: unrecognized arguments: data/Amino-acid-codes2.csv
 
**To Reproduce**
To reproduce, try adding a data file path after otter assign <file> list

**Expected behavior**
I expected my file to be including in the autograder.zip build.

**Versions**
Python 3.8.8
Otter 2.2.5 

**Additional context**
It appears the ability to add data files was removed in January or so; however, I cannot find documentation for how to continue to add files. Is this feature no longer supported?

**Comment by chrispyles** [comment]
This feature is still supported but it is no longer part of the CLI. Most assignment configurations have been moved to the [assignment metadata cell](https://otter-grader.readthedocs.io/en/latest/otter_assign/python_notebook_format.html#assignment-metadata) of the master notebook. In your example, you could include a metadata cell with the contents

````markdown
```
BEGIN ASSIGNMENT
files:
	- data/Amino-acid-codes2.csv
```
````

**Comment by chrispyles** [comment]
Closing this since there's been no reply but please feel free to reopen if there is still an issue.
