### ISSUE TITLE
Can not install otter-grader via pip if R is not installed

### ISSUE THREAD

**Issue by yuvipanda** [ucbds-infra/otter-grader#293]
**Describe the bug**

When installing otter-grader via pip, it tries to install the `rpy2` package. However, `rpy2` package can only be installed if R is installed, and since it is a required dependency, otter-grader pip install fails.

**To Reproduce**

1. Get a clean, python-only environment `docker run -it python:3.8 /bin/bash`
2. Try to install otter-grader with `pip install otter-grader`
3. It'll fail with:
```
WARNING: Discarding https://files.pythonhosted.org/packages/3c/b9/e9f114aee7cc1d86c1e916fee197e35243d115a26130bd4d4a41ac337421/rpy2-3.4.0.tar.gz#sha256=d543e4a577961a24a79cfa3e0c31cdc0169cdcb4b7d80d035f4bcc9df8102d80 (from https://pypi.org/simple/rpy2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading rpy2-3.3.6.tar.gz (179 kB)
     |████████████████████████████████| 179 kB 32.4 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3mg6c2f5/rpy2_620c2b1c5b2f4daea0e84fff410af6c2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3mg6c2f5/rpy2_620c2b1c5b2f4daea0e84fff410af6c2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dme3xtn9
         cwd: /tmp/pip-install-3mg6c2f5/rpy2_620c2b1c5b2f4daea0e84fff410af6c2/
    Complete output (2 lines):
    Error: rpy2 in API mode cannot be built without R in the PATH or R_HOME defined. Correct this or force ABI mode-only by defining the environment variable RPY2_CFFI_MODE=ABI
    cffi mode: CFFI_MODE.ANY
**Expected behavior**
```

**Versions**

Trying to install current version (2.2.5) causes this problem. This issue is not present in 2.2.0.

**Additional context**

Currently, any jupyterhub that doesn't have R installed can use otter-grader. Would be nice to have rpy2 turned into an optional dependency.

**Comment by erniee** [comment]
I have been able to build successfully by adding the following line before the install
ARG RPY2_CFFI_MODE=ABI

**Comment by chrispyles** [comment]
Thanks for the tip @erniee! Since we want R/ottr to be an optional component of Otter, however, I'm still going to remove the required dependency.

I just pushed Otter v2.2.6 which includes this change. @yuvipanda can you try installing that version and let me know if it fixes the error?

**Comment by sean-morris** [comment]
I ran @yuvipanda's steps to reproduce and otter-grader installs. @chrispyles  I will Slack you but I am interested in why this bug popped up now.
