### ISSUE TITLE
Runtime Errors fail to output results.json to Gradescope

### ISSUE THREAD

**Issue by ThaumicMekanism** [ucbds-infra/otter-grader#305]
**Describe the bug**
If `run_autograder` runs into a runtime error, a results.json file is never written to Gradescope so it appears as if there is an unknown Gradescope error instead of an otter-grader derived error.

**To Reproduce**
1. Create an autograder on Gradescope which will cause a runtime error to be thrown.
2. Upload a student submission and you see that the autograder failed to execute correctly instead of giving more information.
<img width="1256" alt="Screen Shot 2021-08-18 at 10 23 47 AM" src="https://user-images.githubusercontent.com/17736421/129943907-2c1dc6fb-b4bc-4701-9d52-2c54495a179e.png">
<img width="999" alt="Screen Shot 2021-08-18 at 9 35 50 AM" src="https://user-images.githubusercontent.com/17736421/129948746-484cbfaf-86d8-4159-b68e-95b7721c83d3.png">

**Expected behavior**
The expected behavior should still return a results.json file to Gradescope even when there is an error given from run_autograder. It should put in the output info about the error and then set a top level output message something describing the base otto-grader. (The details should just go to the autograder output which would be items just printed to stdout). 

**Versions**
Python: 3.7.11
Otter: 2.2.6

**Additional context**
A simple fix would be to wrap https://github.com/ucbds-infra/otter-grader/blob/master/otter/run/run_autograder/__init__.py#L50 so that if any error occurs, it still dumps some helpful message to the results instead of failing all-together. This wrapper would give more info to the instructor about what is causing the error in Otter while also letting students know that Otter had an issue processing some submission.

**Comment by chrispyles** [comment]
@ThaumicMekanism can you share the autograder.zip file and submission you used so I can recreate this output? Feel free to Slack it to me in EECS Crossroads if you prefer.

**Comment by ThaumicMekanism** [comment]
> @ThaumicMekanism can you share the autograder.zip file and submission you used so I can recreate this output? Feel free to Slack it to me in EECS Crossroads if you prefer.

Let me see if I can find it and I will message you through Crossroads

**Comment by chrispyles** [comment]
Discussed on Slack -  arriving at this state seems like a Gradescope issue caused by a container quitting without output but it is still worthwhile to render errors to students e.g. if the submission doesn't contain a gradable file.

**Comment by chrispyles** [comment]
This feature will be included in v2.2.7.
