### ISSUE TITLE
citing otter-grader?

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#313]
**Describe your inquiry** 
Is there a way to cite otter-grader? Preferably there's some Bibtex entry I can add to a `.bib` file. R packages have the `citation()` function which helps, but I'm not aware of anything like this in Python.

**Comment by chrispyles** [comment]
Not sure if this will do everything you what but a quick Google search found [`citepy`](https://pypi.org/project/citepy), which (it seems) scrapes PyPI for the information about Otter. I'm not sure if that's of use but we don't have any set bibtex entry, I'm afraid. The information that this returns, however, is accurate, and I think you could construct a bibtex entry from it.

P.S. if you do end up coming up with something, please share, so we can post it in the documentation. Thanks!

**Comment by tbrown122387** [comment]
`citepy otter-grader` produces 

```
[
  {
    "URL": "https://github.com/ucbds-infra/otter-grader",
    "abstract": "Python and Jupyter Notebook autograder",
    "accessed": {
      "date-parts": [
        [
          2021,
          8,
          22
        ]
      ]
    },
    "author": [
      {
        "literal": "Chris Pyles"
      }
    ],
    "categories": [
      "software",
      "python",
      "libraries",
      "pypi",
      "License :: OSI Approved :: BSD License",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 3"
    ],
    "id": "otter-grader",
    "issued": {
      "date-parts": [
        [
          2021,
          8,
          22
        ]
      ]
    },
    "original-date": {
      "date-parts": [
        [
          2019,
          10,
          5
        ]
      ]
    },
    "publisher": "GitHub",
    "title": "otter-grader",
    "type": "webpage",
    "version": "3.0.0"
  }
]
```

Not quite sure what the entry type and fields are, but maybe something like this (modeled after something [here](https://www.bibtex.com/e/entry-types/))

```
@manual{otter,
      title        = "otter-grader",
      author       = "Chris Pyles",
      organization = "Infrastructure Team at UC Berkeley Data Science Education Program",
      address      = "Berkeley, CA",
      year         = 2019
    }
} 
```

**Comment by chrispyles** [comment]
I think maybe `@misc` would be more appropriate?

```
@misc{ottr
	title = "Otter-Grader: A Python and R autograding solution",
	author = "Christopher Pyles",
	organization = "UC Berkeley Data Science Education Program",
	year = 2019,
	url = "https://github.com/ucbds-infra/otter-grader"
}
```

**Comment by fritterhoff** [comment]
What about the (quite new) feature provided by github: https://github.blog/2021-08-19-enhanced-support-citations-github/ ?

**Comment by hno2** [comment]
> @misc{otter
> 	title = "Otter-Grader: A Python and R autograding solution",
> 	author = "Christopher Pyles",
> 	organization = "UC Berkeley Data Science Education Program",
> 	year = 2019,
> 	url = "https://github.com/ucbds-infra/otter-grader"
> }

I think you are missing a `,` after the starting line. It should be

> @misc{otter,
> 	title = "Otter-Grader: A Python and R autograding solution",
> 	author = "Christopher Pyles",
> 	organization = "UC Berkeley Data Science Education Program",
> 	year = 2019,
> 	url = "https://github.com/ucbds-infra/otter-grader"
> }

**Comment by chrispyles** [comment]
> What about the (quite new) feature provided by github: [github.blog/2021-08-19-enhanced-support-citations-github](https://github.blog/2021-08-19-enhanced-support-citations-github/) ?

Thanks for pointing this out @fritterhoff. I've opened #326 to create this file.

**Comment by chrispyles** [comment]
OK it seems like this question has been answered so I'm going to close this thread, but please feel free to reopen it if there are any other issues.
