### ISSUE TITLE
Autograder.zip is not generated any more

### ISSUE THREAD

**Issue by fritterhoff** [ucbds-infra/otter-grader#319]
The docs (https://otter-grader.readthedocs.io/en/latest/tutorial.html) describe that using the tutorial.zip and executing `otter assign` should generate a autograder.zip.

On my PC that does not happen any more.

**Comment by fritterhoff** [comment]
Ah ... well okay. The issue seems to be somewhere else. 
Sorry. 

I've opened the `demo.ipynb` using VS Code on windows and saved it accidently. Windows changes the linebreaks to `\r\n` so parsing the metadata does not work anymore.

**Comment by chrispyles** [comment]
OK so it seems like this was resolved...?

Closing this but please reopen if there's something I missed.

**Comment by fritterhoff** [comment]
Well, it would be nice If `\r\n` linebreaks work also 🤔

**Comment by chrispyles** [comment]
Fixed with #324
