### ISSUE TITLE
Running otter assign on the tutorial file creates a deprecation warning

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#325]
**Describe the bug**

Running otter assign on the tutorial file creates a deprecation warning

**To Reproduce**

Following the steps in the tutorial on https://otter-grader.readthedocs.io/en/latest/tutorial.html requires running "otter assign" on the provided demo.ipynb file. This generates a deprecation error:

```
(otter-env) instructor@jupyter-lc126:~/tutorial$ otter assign demo.ipynb dist
/opt/conda/envs/otter-env/lib/python3.8/site-packages/otter/assign/__init__.py:34: FutureWarning: Otter Assign format v0 will be deprecated in Otter v4 and removed in a later release.
  warnings.warn(
Generating views...
Generating solutions PDF...
Generating autograder zipfile...
Running tests...
All tests passed!
(otter-env) instructor@jupyter-lc126:~/tutorial$
```

**Expected behavior**

There should be no warning since a tutorial is supposed to be correct.

**Versions**

Python version: 3.8.5
Otter-Grader version: 3.0.1

**Comment by chrispyles** [comment]
The tutorial is correct; the warning is in place because we're trying to make users aware of the new Otter Assign format, since the old version will become deprecated with the release of Otter v4. A new version of the tutorial with the new format is forthcoming.

**Comment by chrispyles** [comment]
Opened #352 which fixes this issue with a reformat of the tutorial to the v1 format.
