### ISSUE TITLE
need explicit instructions for running otter

### ISSUE THREAD

**Issue by aculich** [ucbds-infra/otter-grader#33]
The [README](https://github.com/ucbds-infra/otter-grader/blob/master/README.md) in the documentation describes how to pull the docker image, but then doesn't say anything about how to run otter!

It might help to have an example set of commands to go with the demo notebook that you have available. I managed to run it using something like this on the test notebook in the repo:

```docker rm -f otter ; docker run -it -v $(pwd):/data --name otter ucbdsinfra/otter-grader otter check /data/otter-grader/demo/demo.ipynb```

However that just outputs:

```
otter
0 of 0 tests passed
```

Thanks! -Aaron

**Comment by chrispyles** [comment]
Demo notebook is out of date. We're working on comprehensive documentation but have completed a Getting Started guide at https://otter-grader.readthedocs.io/en/latest/getting_started.html

**Comment by chrispyles** [comment]
Documentation is live! https://otter-grader.readthedocs.io
