### ISSUE TITLE
grade_notebook() not recognizing already executed tests

### ISSUE THREAD

**Issue by TylerADavis** [ucbds-infra/otter-grader#34]
`grade_notebook()` [contains logic for only running tests in tests_glob if they haven't already been run](https://github.com/ucbds-infra/otter-grader/blob/master/otter/grade.py#L65).

At the moment this logic is broken on Gradescope, resulting in all tests being rerun even if they originally passed. This means that the following can now fail

```python
x = 5
grader.check("q1a") # test x == 5
...
x += 2
grader.check("q2a") # test x == 7
```

The autograder will run all tests with the final global environment, resulting in the value of X it sees always being seven.

I tossed some print statements in, (inside the selection logic) and it seems that the issue relates to [logic that assumes executed tests will have short names](https://github.com/ucbds-infra/otter-grader/blob/master/otter/grade.py#L69), but we instead see both already tested tests and ones in the glob have full paths.

```
we ran these: ['/autograder/submission/tests/q1b.py', '/autograder/submission/tests/q1c.py', '/autograder/submission/tests/q2a.py', '/autograder/submission/tests/q3d.py', '/autograder/submission/tests/q4a.py', '/autograder/submission/tests/q4b.py', '/autograder/submission/tests/q4c.py', '/autograder/submission/tests/q4d.py', '/autograder/submission/tests/q4f.py', '/autograder/submission/tests/q4g.py']
We are going to include: /autograder/source/tests/__init__.py
We are going to include: /autograder/source/tests/q1b.py
We are going to include: /autograder/source/tests/q1c.py
We are going to include: /autograder/source/tests/q2a.py
We are going to include: /autograder/source/tests/q3d.py
We are going to include: /autograder/source/tests/q4a.py
We are going to include: /autograder/source/tests/q4b.py
We are going to include: /autograder/source/tests/q4c.py
We are going to include: /autograder/source/tests/q4d.py
We are going to include: /autograder/source/tests/q4f.py
We are going to include: /autograder/source/tests/q4g.py
```

This seems related to the [copying of files](https://github.com/ucbds-infra/otter-grader/blob/05f1c6cd19438220feb044f2aaf898dd36190107/otter/gs_generator.py#L103) between `/autograder/source/tests/` and `/autograder/submission/tests/`. The executed tests are in `/autograder/submission/tests/`, but the glob remains pointed to `/autograder/source/tests/`.

Potential solutions include using [basename](https://docs.python.org/3.8/library/os.path.html#os.path.basename) to compare only the test names or updating the [glob passed into grade_notebook](https://github.com/ucbds-infra/otter-grader/blob/05f1c6cd19438220feb044f2aaf898dd36190107/otter/gs_generator.py#L106) to point to `/autograder/submission/tests/

**Comment by chrispyles** [comment]
Found the bug... forgot to set an argument in run_autograder. #53 fixes this issue

**Comment by TylerADavis** [comment]
Great, thanks for fixing these!
