### ISSUE TITLE
Points default value set to None when unspecified

### ISSUE THREAD

**Issue by abadrinath947** [ucbds-infra/otter-grader#342]
**Describe the bug**
When a question is specified as follows, without the point values unspecified, `otter assign` successfully runs but the autograder fails for those questions.

The following is an example of how a question would look without the point values specified.

![image](https://user-images.githubusercontent.com/40471069/131052833-b475d050-a0a3-4e78-8df1-e3d1a8e8c8df.png)

The following is what is produced in the test:

![image](https://user-images.githubusercontent.com/40471069/131052946-00cb1217-b769-43f0-a052-fc8db7826a9f.png)

The following is the autograder error that results from this:

![image](https://user-images.githubusercontent.com/40471069/131052993-6fe44271-8f88-4754-a154-f19ec843ba89.png)

**To Reproduce**
1. Write a question without points.
2. `otter assign`
3. Check the file or submit to AG.

**Expected behavior**
Points should default to 0 or 1, not None.

**Versions**
Please provide your Python and Otter versions. The Otter can be obtained using `from otter import __version__`
Python 3.9.6 and Otter 3.0.3

**Additional context**

**Comment by chrispyles** [comment]
Resolving this issue as a matter of mis-matched versions of Otter for development and grading.
