### ISSUE TITLE
`otter run` generates an error

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#349]
**Describe the bug**
Running the following code in Jupyter Notebook 
```
from otter.api import grade_submission
grade_submission("autograder.zip", "test-assign-seed.ipynb")
```
generates the following error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/qh/l1jlxh294kv8ddzg803xyrzw0000gn/T/ipykernel_21166/3617444135.py in <module>
      1 # grade_submission("./dist/autograder/autograder.zip","./submissions/test-assign-seed.ipynb")
----> 2 grade_submission("autograder.zip","test-assign-seed.ipynb")

/opt/anaconda3/envs/otter/lib/python3.8/site-packages/otter/api.py in grade_submission(ag_path, submission_path, quiet, debug)
     54     # TODO: is the output_dir argument of run_grader necessary here?
     55     with cm:
---> 56         results = run_grader(submission_path, ag_path, dp, True, debug)
     57 
     58     if quiet:

TypeError: main() takes 1 positional argument but 5 were given
```

**To Reproduce**
1. After running `otter assign ...` and filling answers in `test-assign-seed.ipynb`, place the file and `autograder.zip` in a given folder.
2. Start Jupyter Notebook and set the working directory to the folder using `%cd ..`
3. Execute the cell with the above code.

**Expected behavior**
Returns an `otter.test_files.GradingResults` object.

**Versions**
otter-grader  3.0.4

**Additional context**
macOS Big Sur

[EDIT]
'autograder.zip' and  'test-assign-seed.ipynb' are Assign Format v1.

**Comment by chrispyles** [comment]
Implemented a fix in #351 that will be included in v3.0.5.
