### ISSUE TITLE
calls to `display()` in notebook fail

### ISSUE THREAD

**Issue by TylerADavis** [ucbds-infra/otter-grader#35]
I'm executing otter grader on gradescope, and I've had it fail on a notebook where the student made a call to `display()`. I explicitly set `ignore_errors=False` as I suspected that swallowing the error was causing the student's cell to fail silently, breaking all of the tests dependent on it. I'm not sure if this behavior is expected or not.

```
root@place:/autograder# ./run_autograder 
Traceback (most recent call last):
  File "./run_autograder", line 65, in <module>
    scores = grade_notebook(nb_path, tests_glob, name="submission", ignore_errors=False, gradescope=True)
  File "/usr/local/lib/python3.6/dist-packages/otter/grade.py", line 57, in grade_notebook
    global_env = execute_notebook(nb, secret, initial_env, ignore_errors=ignore_errors, gradescope=gradescope)
  File "/usr/local/lib/python3.6/dist-packages/otter/grade.py", line 202, in execute_notebook
    exec(cell_source, global_env)
  File "<string>", line 12, in <module>
NameError: name 'display' is not defined
```

Student code looks the below. Note, there is no explicit import of display anywhere in the code.
```python
display(df.head()['date'])
```

Requirements.txt that otter generates for gradescope:
```
datascience
jupyter_client
ipykernel
matplotlib
pandas
ipywidgets
scipy
seaborn
sklearn
nb2pdf
tornado==5.1.1
otter-grader==0.4.2
numpy
pandas
seaborn
sklearn
tensorflow
```

**Comment by chrispyles** [comment]
This should be fixed by adding an import of `IPython.display.display` to grade.py. This change is made in #57
