### ISSUE TITLE
`solutions_pdf: true` does not show Japanese

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#356]
**Is your feature request related to a problem? Please describe.**
`solutions_pdf: true` in `# ASSIGNMENT CONFIG`  generates a solution pdf. But Japanese is not displayed.

**Describe the solution you'd like**
Unicode, including Japanese, are correctly displayed.

**Describe alternatives you've considered**
None

**Additional context**
`otter-grader` 3.0.6
Assign Format v1

**Comment by chrispyles** [comment]
@spring-haru can you attach an example notebook that replicates this issue?

**Comment by spring-haru** [comment]
Here is a file, but note that `.txt` is attached to the file name. Please remove `.txt` before using it. Hope it helps.

[assign-seed.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/7072027/assign-seed.ipynb.txt)

**Comment by spring-haru** [comment]
@chrispyles The file sent earlier had unnecessary part for you. I created a minimum example file. As before, the file name is suffixed with `.txt` because GitHub does not allow me to attach an `.ipynb` file. Hope it helps.

[min_example.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/7072363/min_example.ipynb.txt)

**Comment by chrispyles** [comment]
Implemented a fix using the TeX package xeCJK in #357.
