### ISSUE TITLE
otter assign skips Gradescope username/password request even when token is set to None or null 

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#361]
**Describe the bug**
When the notebook metadata contains the line  `token: ''` , otter assign does not ask for the Gradescope username/password. The same is true if the line `token: None` or `token: null`.

**To Reproduce**
Add the line above to the metadata of a notebook and run "otter assign" on the notebook.

**Expected behavior**
Since Gradescope tokens are nonempty strings, in all these cases otter assign should assume that a Gradescope token has not been specified, and should ask for Gradescope username/password.

**Versions**
Python version: 3.8.5
Otter-Grader version: 3.0.6

**Additional context**
A workaround is to comment out the line. However, I am trying to create a file that contains all of the metadata settings and it would be convenient to be able to include the "token" line.

**Comment by chrispyles** [comment]
Implemented a fix in #374 which will be included in v3.1.0.
