### ISSUE TITLE
Provide submission export for R notebooks

### ISSUE THREAD

**Issue by chrispyles** [ucbds-infra/otter-grader#369]
Provide functionality like `otter.Notebook.export` but for R notebooks.

**Comment by dbroockman** [comment]
Per our conversation, just posting some more detail here so you have it.

You suggested an interim fix, which is to add an R cell like this to the bottom of the notebook:

```
nb_name <- "Test_Assignment.ipynb"
system(paste0("python3 -c 'import otter; otter.Notebook(\"", nb_name, "\").export()'"))
fp = tail(sort(Sys.glob("*.zip")), n=1)
IRdisplay::display_html(paste0("<a href='", fp, "' download='", fp, "'>Download your submission</a>"))
```

I've tested this and this **does** work on Gradescope.

I also tried a version where I put lines 2-4 of the above in a separate .R file to hide some of the ugliness for students. However, that approach does **not** work on Gradescope, and yields these errors.

<img width="633" alt="Screen Shot 2021-08-31 at 10 23 01 PM" src="https://user-images.githubusercontent.com/6677808/131620878-75f74283-15bf-4d36-9349-75e49b5090b4.png">
<img width="499" alt="Screen Shot 2021-08-31 at 10 22 01 PM" src="https://user-images.githubusercontent.com/6677808/131620882-36b81e71-5e22-4cfb-a9b5-abea637d6456.png">

**Comment by dbroockman** [comment]
P.S. In the long run, would be nice to have the R notebook submit itself to Gradescope without students having to upload manually, which is what I understand the Python notebooks do.

**Comment by chrispyles** [comment]
Implemented `ottr::export` in https://github.com/ucbds-infra/ottr/pull/9

**Comment by chrispyles** [comment]
Implemented required Python functionality in #370

**Comment by chrispyles** [comment]
@dbroockman I've just merged #370, so the new functionality for export cells with Otter Assign will be included in Otter v3.1.0.

The `ottr::export` function is already included in Ottr v1.1.0, so if you want to use that instead of the script you can.

```r
devtools::install_github("ucbds-infra/ottr@1.1.0")
```

```r
ottr::export("notebook.ipynb")
```

As a side note, the Python version does _not_ auto-upload submissions to Gradescope; their API is limited to instructors only, so students can't submit to it. This is a feature we hope to add for all versions of Otter, but can't until that is changed.

**Comment by dbroockman** [comment]
To use this new functionality, do I just add `ottr::export("notebook.ipynb")` to the bottom of a notebook and then Otter compile it?

You noted that a "reminder [to save] is also included a couple times in the new export cells w/ v3.1.0" but when I put in a cell with `ottr::export("notebook.ipynb")` in the bottom of my source notebook and then run Otter, I don't get any extra text at the end.

**Comment by chrispyles** [comment]
Are you using Otter Assign to generate this notebook? Otter Assign is what includes the reminders, not calling `otter::export`.

**Comment by dbroockman** [comment]
Yes.

I might not be including the export cell right. All I did was include a cell in the source notebook that said `ottr::export("notebook.ipynb")` and then compiled the notebook using `otter assign`.

I attached an example notebook to this message: https://otter-grader.slack.com/archives/D02DAAAUB6F/p1631160558001400

**Comment by chrispyles** [comment]
@dbroockman from the notebook you sent me the reason is because you're using Otter Assign v0 format, inwhich the update to automatically include export cells was not included. Since v0 is an old format, it is no longer under active development.

I suggest updating your notebooks to the v1 format if you want to use this feature, or adding the cells which include the reminder manually.

Otter v3.1 includes a tool that will convert the notebooks to the new format for you; more details in the [docs](https://otter-grader.readthedocs.io/en/latest/otter_assign/index.html#converting-to-v1).
