### ISSUE TITLE
Error when students submit notebook contains ...

### ISSUE THREAD

**Issue by quan3010** [ucbds-infra/otter-grader#371]
Hi, I just want to raise this issue to your attention. 

I created a test Jupyter Notebook running R. It passed the otter assign and I was able to upload the autograder.zip to Gradescope. However, there's some strange behaviour when students submit a notebook with the `...`

Basically when we write something like `answer = 123 # SOLUTION` , the student version will be `answer = ...` However, if the student did not fill in the `...` and submit their notebook with the three dots, the AG will throw an error  `R[write to console]: Error in right_expr[[1]] : object of type 'symbol' is not subsettable`. NOTE: Maybe this is just something in R

The work around is to do design something like this in the source file
`answer = 123 # SOLUTION NO PROMPT`
`answer = NULL`
The line ending with `# SOLUTION NO PROMPT` will be removed in student version. So what students will see is `answer <- NULL` . And even if the student did not do that question and submit the notebook, the AG will not throw an error.

**Comment by chrispyles** [comment]
Thanks for pointing this out. I think there is a related issue that's cropped up in the Otter slack. But I think it might be worthwhile to implement a separate fix for this, like what we do in Rmd files:

```
answer = 123 # SOLUTION
```

would get replaced with

```
answer = NULL # YOUR CODE HERE
```

instead of `...`.

**Comment by chrispyles** [comment]
Implemented this change in #372 and will be included in v3.1.0.
