### ISSUE TITLE
Otter assign fails in 3.1.1 due to a Latex issue (emergency stop)

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#381]
[assignment01-Copy1.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/7132084/assignment01-Copy1.ipynb.zip)

Running "otter assign" on the attached assignment succeeds in otter v3.0.6 but fails in 3.1.1 due to a Latex issue that leads to an emergency stop.

To reproduce, run "otter assign assignment01-Copy1.ipynb dist".

Running Python 3.8.5.

```
(otter-env) instructor@jupyter-lc126:~$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

A similar bug was identified on https://github.com/berkeley-dsep-infra/datahub/issues/2714. The workaround suggested there, consisting of updating the Tex Live installation, does not work for me because I don't have write permissions to /usr/share.

**Comment by chrispyles** [comment]
There isn't much that can be done from Otter's end about this. I suggest contacting whoever manages your hub to see if your installation of the fandol font (which is the underlying issue causing the issue you referenced) can be fixed.

**Comment by chrispyles** [comment]
https://github.com/ucbds-infra/otter-grader/blob/master/otter/export/exporters/templates/via_latex.tpl
