### ISSUE TITLE
GradeScope, Hidden Tests and Otter Grader

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#383]
**Describe your inquiry** 
Quick question on GradeScope and Otter Grader. 

In HW#2, for example, there are several hidden tests. The students are submitting the notebook to Gradescope, the tests run, the student gets a hundred percent and does not see that they are failing some or all of the hidden tests. The teacher can see the failed hidden tests. The student thinks everything is correct but when the score is displayed they then see the actual score.

Here are screenshots below:
Teacher view showing the failure of the hidden tests but all else passed:
![image](https://user-images.githubusercontent.com/1514995/132605031-b6abb729-abed-4500-85fd-79b06278abbf.png)

My view as a student for this submission:
![image (1)](https://user-images.githubusercontent.com/1514995/132605115-16b67d99-ca30-43cb-ba49-f35bfba050fa.png)

It seems a bit funky that the student thinks they got 100%, did not get 100% but also does not know what they missed. It seems like it should at least indicate that they failed hidden tests associated with particular problems. 

Am I missing something? Is there a switch to flip that would tell them a score that included the hidden tests when they submit the notebook?

Thanks

**Comment by chrispyles** [comment]
1) It looks like you're using an outdated version of Otter (v2.1.1 from the screenshot).
2) To show students a summary of their score, you can set  `show_stdout` to true in your `otter_config.json` (or set `generate: show_stdout: true` if using Otter Assign) to show students the stdout of the grading process (the "Autograder Output" section above), which includes a printed dataframe with a summary of scores by question.

**Comment by sean-morris** [comment]
Perfect thanks
