### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by andreabartolucci** [ucbds-infra/otter-grader#389]
I have followed the tutorial but I am having some problems in the last step (otter grade The submission_pdfs are produced but not final_grades.csv. Here attached you can find the screenshot of the error and some other screenshots that document the steps I have followed.
The error is "PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Andrea\\AppData\\Local\\Temp\\tmpqxnqpv19" and it seems to happen here File "c:\users\andrea\anaconda3\envs\gsas\lib\site-packages\otter\grade\containers.py", line 210, in grade_assignments  os.remove(temp_subm_path)
![Screenshot (533)](https://user-images.githubusercontent.com/73433596/132834975-f6ebdd73-bdb2-4533-8b10-797f886b5c78.png).
![Screenshot (534)](https://user-images.githubusercontent.com/73433596/132834980-5e3c626b-02f6-4807-9fc7-15f313102950.png)
![Screenshot (535)](https://user-images.githubusercontent.com/73433596/132834982-09ec7eb2-910f-4f33-b439-696cc01df242.png)
![Screenshot (536)](https://user-images.githubusercontent.com/73433596/132834986-afb8a0bf-bad6-4110-815a-4b5f452a2932.png)

**Comment by chrispyles** [comment]
@andreabartolucci I think I've found the issue and fixed it. Do you mind re-installing Otter from my fork and verifying that this fix works?

```
pip uninstall -y otter-grader
pip install git+https://github.com/chrispyles/otter-grader.git@master
```

**Comment by andreabartolucci** [comment]
Dear Chris,

 

Awesome, everything works fine!

 

Andrea
