### ISSUE TITLE
otter.assign.utils.AssignNotebookFormatException show more informative error messages

### ISSUE THREAD

**Issue by eroubenoff** [ucbds-infra/otter-grader#398]
When using otter assign, error messages display the cell number where the error occurs, which isn't necessarily trivial to find in a larger notebook. For ex, in the following message, it isn't necessarily easy to find cell 143 without counting. Could this message display the question metadata, like, `Found a begin question <<question name>> cell inside another question <<question name>>`?

![image](https://user-images.githubusercontent.com/27761163/133000702-c7e61085-3810-4a9e-8b24-42b6531a729b.png)

Thank you!

**Comment by chrispyles** [comment]
Good suggestion @eroubenoff! I've opened #399 which updates the exception message to look like this:

```
otter.assign.utils.AssignNotebookFormatException: Found a begin question cell inside another question (question q2_3, cell number 57)
```
