### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by TylerADavis** [ucbds-infra/otter-grader#40]
The gradescope otter docs link to the below link, but it 404s

Page linking: https://otter-grader.readthedocs.io/en/latest/gradescope.html
Link: https://otter-grader.readthedocs.io/en/latest/test_files.md#ok-format-caveats
Possible correct link: https://otter-grader.readthedocs.io/en/latest/test_files.html#ok-format-caveats

(.md -> .html)

**Comment by chrispyles** [comment]
Thanks for catching that. I guess sphinx doesn't autoconvert .md to .html when there's an anchor id in the link.
