### ISSUE TITLE
remote link to tests folder?

### ISSUE THREAD

**Issue by johnchaston** [ucbds-infra/otter-grader#400]
**Is your feature request related to a problem? Please describe.**
If i have to change one test, I have to rebuild the entire docker image.

**Describe the solution you'd like**
Is it possible to submit a link to the folder containing the tests? My goal is to build the docker image one time and then add, delete, or modify files in the 'tests' folder remotely so that I don't have to freshly build a docker if I find an error in one of the tests. I think i would use something like a dropbox link or a private GitHub link.

**Describe alternatives you've considered**
Rebuilding the image each time definitely works.

**Additional context**

**Comment by chrispyles** [comment]
Currently, this is not possible. But one thing we could do is provide a way of mounting a local directory of tests inside the Docker image at the appropriate path and leaving the tests out of the zip file. Then you wouldn't need to rebuild the image when tests change.

I'll look into this.

**Comment by chrispyles** [comment]
Wait- is this inquiry about running locally or on Gradescope?

**Comment by johnchaston** [comment]
Ah, yes, this was about running on Gradescope, sorry for not clarifying. No big deal, mostly just wondered if there was a trick I hadn't seen in the documentation. I really love the software and the great support, too.

**Comment by chrispyles** [comment]
Yeah, sorry, there's no trick like that. The issue is managing the credentials inside the image in such a way that the autograder can pull in the tests without the student being able to leak them.
