### ISSUE TITLE
Showing output to students for debugging purposes

### ISSUE THREAD

**Issue by quan3010** [ucbds-infra/otter-grader#410]
Hi team,

I am using Gradescope and I would like to display the autograder output when a notebook failed to run to students so they can debug their own notebooks. Currently, only instructors can see the log of the errors but the students cannot. 

According to Gradescope, I need to change the "stdout_visibility" in results.JSON file but there is no results.JSON file when I run otter assign. 

How can I configure this?
Thanks,
Quan

**Comment by chrispyles** [comment]
Currently, Otter swallows all notebook errors, so even if the stdout of the grading process was visible to students, they wouldn't be able to see any errors thrown.

Is your goal to show students their score information before the deadline? Or to inform them of when an error occurs while running their notebook, without displaying any score information?

**Comment by quan3010** [comment]
@chrispyles  My goal is to help students debug their own errors instead of having to go back to instructors every time their notebooks failed to run. As of now, students see their notebook failed but without knowing why.

**Comment by chrispyles** [comment]
Is this for cases in which the autograder runs successfully (i.e. it outputs some kind of results file to Gradescope) but student-submitted code has errors or when the autograder itself breaks?

**Comment by quan3010** [comment]
This is when the autograder itself breaks. It displays this message to students `The autograder failed to execute correctly. Contact your course staff for help in debugging this issue. Make sure to include a link to this page so that they can help you most effectively.` 

As instructors, I can see the log output and where the errors occur. I want students to be able to see the same log output

**Comment by quan3010** [comment]
As instructor I can see the log output like this, which helps debugging the errors in students submission

Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 11, in <module>
    run_autograder('/autograder')
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 51, in main
    output = run_autograder(options)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/r_adapter/run_autograder.py", line 92, in run_autograder
    output = r(f"""ottr::run_autograder("{fp}")""")[0]
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/rpy2/rinterface.py", line 680, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in parse(text = script) : <text>:106:32: unexpected symbol
105: ## -----------------------------------------------------------------------------
106: "Linda is a UBC MDS graduate " is

**Comment by chrispyles** [comment]
What version of Otter are you using? This looks like an old version.

**Comment by quan3010** [comment]
Otter-Grader version: 3.0.3

**Comment by chrispyles** [comment]
This was an issue that was fixed in Otter v3.1.0. We made it so that R code that was syntactically incorrect wouldn't break the AG. I would recommend upgrading to the latest version of Otter to see if that fixes your issue.

Besides that, there isn't a way to directly alter the results.json that Otter produces for Gradescope except by writing a plugin. If you'd like to look into that, you can find information about Otter's plugin system in the [docs](https://otter-grader.readthedocs.io/en/latest/plugins/index.html). However, I do think that the improvements made with Otter v3.1 will fix a lot of the issues you're experiencing, so I'd recommend trying that first.

**Comment by quan3010** [comment]
Hi @chrispyles , does the new version of otter (3.1.4) automatically generate a submission cell at the end of a notebook. What is up with this otter::export ?

**Comment by chrispyles** [comment]
Yes, this was added in Otter v3.1. `ottr::export` just puts the student's notebook into a zip file to prevent downloading issues.

**Comment by chrispyles** [comment]
https://github.com/ucbds-infra/otter-grader/issues/369

**Comment by chrispyles** [comment]
Closing as it seems like the issue was resolved but please reopen if that's not the case.
