### ISSUE TITLE
How fast should Docker grading be?

### ISSUE THREAD

**Issue by hgibling** [ucbds-infra/otter-grader#413]
I'm wondering how fast I should expect autograding to occur when done with docker. Testing 2 submissions for an assignment with 2 short answers, the `otter grade` step took ~12 minutes. I thought that after the image was first built, grading subsequent assignments would be quicker, but that doesn't seem to be the case. I also tried running `otter grade --no-kill` and then running the autograding on a second 2-question assignment, but it still took ~12 minutes. I have limited docker experience so I'm not sure if this is normal or if this can be streamlined in any way. I'm not closing Docker or stopping any images in between attempts.

If this is the expected speed, I could use `otter run` and set up a script to run through all of the submissions in succession. But since we don't use GradeScope at my institution, it would be great if there was an output option for a plain text csv/tsv table. It's technically there in the stderr output, but I'd have to parse out the ascii otter logo first. Just a thought :)

```
Docker version 20.10.8, build 3967b7d
Python version: 3.7.9
Otter-Grader version: 3.1.3
```

**Comment by fritterhoff** [comment]
Are you using windows or linux/mac as underlying os?

**Comment by hgibling** [comment]
Whoops, sorry. Mac, Big Sur 11.6

**Comment by fritterhoff** [comment]
Building the docker image for grading inside docker can take some time (normally a few minutes), the grading step it self should be done in a few seconds.
You mention, that you grade two different assignments? I assume that both have a different autograder.zip? That will cause building different docker images. I would expect that grading the same submissions again should be far faster because the images are already built.

**Comment by hgibling** [comment]
Yes, the plan will be to grade multiple assignments, but each assignment only once. I guess it just isn't as fast as I was expecting it to be.
Thanks!

**Comment by chrispyles** [comment]
Seems like this has been resolved so I'm closing this issue but feel free to reopen if that's not the case.
