### ISSUE TITLE
Cannot configure success/failure message in test cells in Rmarkdown

### ISSUE THREAD

**Issue by quan3010** [ucbds-infra/otter-grader#416]
I used the example .Rmd here https://github.com/ucbds-infra/otter-grader/blob/master/test/test-assign/rmd-example.Rmd

I changed the q1d test to public instead of hidden.
```{r}
" # BEGIN TEST CONFIG
name: q1d
hidden: false
success_message: congrats
" # END TEST CONFIG
test_that("q1d", {
    expect_equal(as.character(x), "2")
})
```
I ran otter assign to create a student version (otter v3.1.3)

I filled out the solution (x <-2) then ran the otter::check. It shows "All tests passed!" instead of the "congrats" message 
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/48820406/135344775-da59bc93-627a-41da-be7b-ab6f9eaea2bc.png">

**Comment by chrispyles** [comment]
OK I've fixed the issue with Ottr v1.1.3. The default version in Otter's grading images is changed with #421. You can upgrade to this version of ottr locally using `devtools::install_github`.
