### ISSUE TITLE
How do I get messages specified in "success_message" to display?

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#425]
How do I get messages specified in "success_message" to display? When I specify a success_message and a failure_message in a public test, and run the test as a student on a correct input, it just says "Test so-and-so passed" but doesn't show the success_message. When I run it on incorrect input, it shows the output of the test and then the failure_message. Example assignment is attached.
[assignment01.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/7325661/assignment01.ipynb.zip)

**Comment by chrispyles** [comment]
@champoll will take a look at the example you provided.

@joelostblom what version of ottr are you using? I believe this was fixed with ottr v1.1.3?

**Comment by chrispyles** [comment]
@champoll I've opened #432 which fixes this issue and will be included in v3.2.0.

**Comment by joelostblom** [comment]
Yes this was fixed when I upgraded to 1.1.3, thanks!
