### ISSUE TITLE
R tests not run when executing `otter assign`

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#427]
For Python notebooks, all tests will be executed when running `otter assign`, which is great to check that there are not typos in the solutions and the tests. For R notebooks, the tests are not run when executing `otter assign` and I need to run `otter run` separately afterwards to check if the tests are set up correctly. It would facilitate working with multiple languages if Otter acted consistently across them, so that the expectations when creating R and Python assignments is the same, preferably that tests are always run when executing   `otter assign`.

**Versions**
Ottr 1.1.3
Python 3.9.7

**Comment by chrispyles** [comment]
I think a good way of doing this would be transitioning to grading the autograder output using Otter Run instead of calling `grade_notebook` correctly (similar to the zip validation in `otter.Notebook.export`). Will take a look at this for v5.
