### ISSUE TITLE
Output test messages from test_that so that students can see the feedback on what is wrong

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#428]
`test_that` allows to input a custom error message, e.g. 

```
test_that('Always false', expect_true(FALSE))
```

Unfortunately these are not shown by Otter, that instead just display "Test failed" as in this screenshot:

![image](https://user-images.githubusercontent.com/4560057/137205352-853ff16a-5476-4221-97dc-074929e19fa5.png)

It would be great if these were shown to students instead of having to set the cell test metadata failure message with the same string that is already supplied to testthat.

Also note that Otter evaluates the test above incorrectly as TRUE on testhat < 3.1.0 (and I think >= 3.0) and just displayed "Test passed".

**Comment by chrispyles** [comment]
Ottr v1 does not support wrapped tests in calls to `testthat::test_that` because it determines the passing or failing of a test based on whether an error is raised; `test_that` swallows errors so the test will always appear as "passed," hence the issue you referenced. I think it would be better to just specify the failure_message in the test metadata and not use `test_that`, e.g.

```r
" # BEGIN TEST CONFIG
failure_message: Try again
" # END TEST CONFIG
testthat::epect_true(FALSE)
```

**Comment by hgibling** [comment]
@chrispyles it doesn't seem like test metadata set up for Rmd, correct? It would be great if it was!

**Comment by chrispyles** [comment]
@hgibling test metadata is set up for Rmd.

**Comment by hgibling** [comment]
@chrispyles It seems to work for `hidden: true`, but not the success or failure messages. 

Assignment: https://github.com/hgibling/otter-test/blob/main/A4.Rmd
Student Version: https://github.com/hgibling/otter-test/tree/main/dist/A4/student

**Comment by chrispyles** [comment]
What version of ottr are you using? I am seeing the messages with v1.1.3:

<img width="726" alt="Screen Shot 2021-11-12 at 9 45 47 PM" src="https://user-images.githubusercontent.com/40970945/141607448-a298e2c3-8ae4-4618-b285-c23b2e3ab7ea.png">
