### ISSUE TITLE
Conda cannot resolve conflicts with `--set channel_priority strict`

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#430]
Trying to install environments with `conda config --set channel_priority strict` is faster but more likely to end in unresolvable conflicts. Using this as the default options is likely to break autograder.zip when specifying specific package versions in the autograder env files. I am running into this with `R==4.1.1` and have to manually edit the zip file's setup.sh to remove the line with the strict channel prio. It would be helpful if this could be made an option in the the notebooks metadata instead of manually applying a fix.

Otter 3.1.4, Python 3.9.7

**Comment by chrispyles** [comment]
The reason this was added was that the environment build kept getting killed because it ran out of memory without it (cf. #386 and #392). Have you experienced any similar issues with removing it?
