### ISSUE TITLE
Make question prompt cells read-only for students

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#431]
**Is your feature request related to a problem? Please describe.**
When students accidentally edit or delete a question prompt instead of the following answer prompt,  the `<!-- BEGIN QUESTION -->` tag can get disturbed. This prevents their manually graded answers from appearing properly in their submission, resulting in confusion because graders cannot distinguish their submission from a missing answer.

**Describe the solution you'd like**
Ideally, question prompt cells would be read-only in the student-facing notebooks.

**Describe alternatives you've considered**
As an alternative, the exported PDF could have an error message so that the graders can distinguish the submission from a missing answer.

**Comment by ericvd-ucb** [comment]
I think the way that you do this is you edit the cell meta data to make the cell not editable
I just saw an example of this the other day in and Econ 140 homework
https://github.com/ds-modules/ECON-140-SP21/blob/main/ps3/ps3.ipynb

The author used the notebook metadata to lock the cells 'editable'
```
 "deletable": false,
  "editable": false

```
Which you get to by using view - edit cell metadata

![image](https://user-images.githubusercontent.com/30128480/139923013-a758dfa0-056c-43b5-a4e1-af9614bd4413.png)

**Comment by champoll** [comment]
Thank you @ericvd-ucb ! This is helpful but suboptimal since the cells whose metadata I would need to edit are only present in the output of otter assign, and will be erased and recreated without the metadata every time I rerun otter assign. On the other hand, since these cells are created by otter assign, it seems that the tool should be able to add the metadata.

**Comment by ericvd-ucb** [comment]
I guess I dont know the answer  - but if you go ahead and lock them in the Instructor notebook, maybe they result as locked in the student notebook? Did you try this already?

**Comment by champoll** [comment]
Yes, that worked -- thank you! (Sorry for the late answer.) 
@chrispyles It would be great if there was a way to do this automatically by default -- I can't think of a reason why we should allow students to be able to edit the question prompts.

**Comment by chrispyles** [comment]
#560 should fix this issue.
