### ISSUE TITLE
Include .pdf export in `ottr:export()` generated .zip file

### ISSUE THREAD

**Issue by dbroockman** [ucbds-infra/otter-grader#440]
**Is your feature request related to a problem? Please describe.**
Students using R Notebooks write answers to free response questions, then use `ottr::export()` to download .zip files, which they then upload to Gradescope. GSIs grading the questions must navigate pages of code to find the free response answers, instead of being able to read a clean PDF of just the free response questions.

**Describe the solution you'd like**
`ottr::export()` exports a .zip file that includes a PDF with answers to the free response questions only. GSIs grading the questions can view a PDF that has just the free response questions, making the grading much quicker.

**Describe alternatives you've considered**
Right now GSIs must manually scroll down to the appropriate questions.

**Comment by dbroockman** [comment]
Just to say - this is still of interest to us! 😀

**Comment by chrispyles** [comment]
ottr now supports generating PDFs as of v1.3.0. To use it, set `pdf = TRUE` in `ottr::export`. There is some remaining work to make Otter Assign set this instead of needing to do it manually, which will be included in otter v4.3.0.
