### ISSUE TITLE
Prevent students from submitting to the wrong autograder

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#442]
**Is your feature request related to a problem? Please describe.**
I use Gradescope to grade assignments and I often have more than one assignment released at the same time. Students sometimes accidentally submit to the wrong slot. E.g. they will work on Assignment X and submit to Assignment Y. The autograder of Assignment Y will nevertheless grade their assignment if the assignments share the same question names.  Students may not notice their error until after the due date has passed. 

**Describe the solution you'd like**
If assignment X is submitted to autograder Y, the autograder should produce a user-friendly error and refrain from assigning a score.

**Describe alternatives you've considered**
I work around this by monitoring submissions by hand but it gets exhausting.

**Comment by champoll** [comment]
I am still interested in this!

**Comment by chrispyles** [comment]
This has been implemented with #500 and will be included in v4.

To use this feature, set the new `name` key in the assignment config of your otter assign master notebook. Details will be in the [beta docs](https://otter-grader.readthedocs.io/en/beta/otter_assign/v1/notebook_format.html).

**Comment by chrispyles** [comment]
(Looks like the docs build is actually not working atm and I'm not sure when I'll be able to fix it. You can find the instructions in the docs source files though: https://github.com/ucbds-infra/otter-grader/blob/beta/docs/otter_assign/v1/notebook_format.rst.)
