### ISSUE TITLE
Many students receiving "Notebook ... is empty" error

### ISSUE THREAD

**Issue by davidwagner** [ucbds-infra/otter-grader#444]
**Describe the bug**
On Project 2 in Data 8, many students are experiencing the following error message when trying to run the grader.export cell.

```
grader.export(pdf=False, force_save=True)
[...]
AssertionError: Notebook project2.ipynb is empty. Please save and checkpoint your notebook and rerun this cell.
```

In particular, here is the full error message:

```
<IPython.core.display.Javascript object>

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_125/3138762564.py in <module>
      1 # Save your notebook first, then run this cell to export your submission.
----> 2 grader.export(pdf=False, force_save=True)

/opt/conda/lib/python3.9/site-packages/otter/check/utils.py in colab_only_method(self, *args, **kwargs)
     96         if self._colab:
     97             raise RuntimeError("This method is not compatible with Google Colab")
---> 98         return f(self, *args, **kwargs)
     99     return colab_only_method
    100 

/opt/conda/lib/python3.9/site-packages/otter/check/utils.py in run_function(self, *args, **kwargs)
    130                 except Exception as e:
    131                     self._log_event(event_type, success=False, error=e)
--> 132                     raise e
    133                 else:
    134                     self._log_event(event_type, results=results, question=question, shelve_env=shelve_env)

/opt/conda/lib/python3.9/site-packages/otter/check/utils.py in run_function(self, *args, **kwargs)
    125                         question, results, shelve_env = f(self, *args, **kwargs)
    126                     else:
--> 127                         results = f(self, *args, **kwargs)
    128                         shelve_env = {}
    129                         question = None

/opt/conda/lib/python3.9/site-packages/otter/check/notebook.py in export(self, nb_path, export_path, pdf, filtering, pagebreaks, files, display_link, force_save, run_tests)
    300         try:
    301             with open(nb_path) as f:
--> 302                 assert len(f.read().strip()) > 0, \
    303                     f"Notebook {nb_path} is empty. Please save and checkpoint your notebook and rerun this cell."
    304 

AssertionError: Notebook project2.ipynb is empty. Please save and checkpoint your notebook and rerun this cell.
```
I am suspicious that perhaps the "save" failed, but I'm not sure.

**To Reproduce**
1. Go to [Project 2](http://data8.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/data-8/materials-fa21&subPath=materials/fa21/project/project2/project2.ipynb) in Data 8
2. Run the first two cells (`# Initialize Otter` and `# Run this cell`).
3. Scroll down to the first `grader.export` cell and run that cell.
4. See the error shown above.

**Expected behavior**
This should successfully save and export the notebook to a zip file.

**Versions**
Otter 3.1.4, Python 3.9.7.

**Comment by chrispyles** [comment]
There's really not much that can be done about this error. This happens when the notebook save takes so long that the Otter's auto-save times out but the save actually occurs when the zip file is being generated. I can increase the default timeout so that it waits longer before continuing but that won't guarantee that the problem never occurs.

Unfortunately, auto-save is very finicky (a caveat I emphasized when discussing its use with the Data 8 team). The only way of preventing this entirely is not using auto-save (which students can do by making the export cell editable and removing `force_save=True`).

**Comment by davidwagner** [comment]
Got it.  So not an issue in Otter then.  I don't think changing the timeout is worthwhile.  The Jupyter hub servers are overloaded, which is why the auto-save is failing.  Sorry to take up your time on this, and thank you for your rapid response.
