### ISSUE TITLE
More robust version of force_save

### ISSUE THREAD

**Issue by davidwagner** [ucbds-infra/otter-grader#450]
**Is your feature request related to a problem? Please describe.**
Currently the force-save implemented by `grader.export(force_save=True)` is flaky and we have observed it sometimes failing in Data 8.  When it fails, the student sees an error message and then is completely stuck: there is nothing they can do to submit their assignment.

**Describe the solution you'd like**
It would be nice to have some code to make this more robust, so it is less likely to fail, or so that if it fails, it fails more gracefully and students can still submit.

A retry loop would be useful, with some limited number of attempts (e.g., 5).  Also, if the save fails, it would be useful to show a warning message (e.g., "Couldn't automatically save the notebook, we recommend using File > Save & Checkpoint and then re-running this cell") and then proceed to generate a zip file anyway and display a message with a link to the zip file (rather than failing without generating a zip file).

**Describe alternatives you've considered**
A possible alternative is to increase the timeout, but I'm concerned that if it takes more than 10 seconds to save, it might take an unlimited amount of time.

**Additional context**
#444, #447, https://github.com/ucbds-infra/otter-grader/blob/6a33a7519c8015201989250a1d185d4b03638892/otter/check/utils.py#L18

**Comment by chrispyles** [comment]
I think #476 goes towards a more robust implementation of the force-save feature. I've also used it to update the warning displayed to students.
