### ISSUE TITLE
Autograder terminated improperly without error message on gradescope 

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#451]
I am seeing this message on gradescope for an R notebook:

```
The autograder terminated improperly without reporting results back to Gradescope.
You may want to investigate the autograder and student code to see why this might have happened.
```

There are no additional details and the autograder runs fine locally on the same notebook. It seems to be related to using the function `plot_grid` from the `cowplot` package. Are there any known issues with this package or any suggestions for how to troubleshoot this to find out what the underlying issue is?

**Comment by chrispyles** [comment]
I haven't heard about any issues regarding that package. On Gradescope, you can debug a submission using Gradescope's Debug via SSH feature. In the container, set `"debug": true` in `/autograder/source/otter_config.json` and then run `/autograder/run_autograder` to run the AG. When `debug` is true, Otter won't swallow errors raised by the submission.

**Comment by joelostblom** [comment]
Thank you @chrispyles, your troubleshooting tips were really helpful. It turns out that this error came from using cowplot together with a plot that depended on the Hmisc package (which was not installed and caused a prompt to occur which timed out the autograder). No idea why it is only triggered when used together with cowplot and not when displayed alone as in one of the previous questions which made this difficult to troubleshoot, but how R works is often a mystery  to me so :man_shrugging:
