### ISSUE TITLE
Resolving point values: yet another case?

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#460]
**Describe your inquiry** 
It is about how to resolve point values. I did the following:

* No point value is specified for the question.
* `0` is specified for some tests, while no point value is specified for the remaining tests.

The result is
*  each of point-unspecified test case is equally weighted with a point value of `1/n` where `n` is the number of point-unspecified test cases.

Is this an expected result? This case is not explained in the doc as far as I can see.

otter-grader 3.2.0

**Comment by chrispyles** [comment]
Yes, this behavior is described here: https://otter-grader.readthedocs.io/en/latest/otter_assign/v1/notebook_format.html#test-cells

**Comment by spring-haru** [comment]
I am relieved that it is a default behavior, because  I will use it often. However, I am not sure that the case in point is described in the link. There are four cases there (the same order):

1. If one or more test cases DO specify a point value and NO point value is specified for the question, ....
2. If  one or more test cases DO specify a point value and a point value IS specified for the question,....
3. If NO test cases specify a point value and a point value IS specified for the question,....
4. If NO test cases specify a point value and no point value IS specified for the question,....

The case I raised is closest to 1. Perhaps, to accommodate the case, 1 could be rephrased as

"If one or more test cases specify a POSITIVE point value and no point value is specified for the question, each test case with unspecified point values is assumed to be worth 0 points."

together with

"If one or more test cases specify a ZERO point value and no point value is specified for the question, each test case with unspecified point values is equally weighted with a point value of `1/n` where `n` is the number of point-unspecified test cases."

Or am I missing something?

**Comment by chrispyles** [comment]
That's a good point-- this case isn't covered here. I think what I'll do is change the language of the first item to

> If one or more test cases specify a point value and no point value is specified for the question, each test case with unspecified point values is assumed to be worth 0 points unless all test cases with specified points are worth 0 points; in this case, the question is assumed to be worth 1 point and the test cases with unspecified points are equally weighted.
