### ISSUE TITLE
do otter grader public tests support reference of variables or custom functions that never become visible to students?

### ISSUE THREAD

**Issue by timothylwarren** [ucbds-infra/otter-grader#465]
Perhaps my question could be best stated in terms of an example:

In lowest prime demo example, students are asked to set `lowest_prime` to 2.
A direct test of the correct answer would be <br>
`assert np.isclose(lowest_prime, 2)`
but this would give away answer.

Is there a way to set a variable `correct_answer` that is not visible to students so test could be <br>
`assert np.isclose(lowest_prime,correct_answer)`.

`correct_answer=2` 
could be put in solution with no prompt but for more complicated cases (e.g. where public test involves a custom, hidden function, this would be undesirable)

**Comment by timothylwarren** [comment]
Realized that simple solution is to put these extra statements (and function definitions) within Test area and that they don't count as tests without assertions.

**Comment by timothylwarren** [comment]
Reposting my original question - because I see that when students put wrong answer, every statement in test area is treated as test and revealed to students, even if they don't raise errors.

So, in above example, putting `correct_answer=2` in the test would reveal the answer to the student if they got the wrong answer.

**Comment by chrispyles** [comment]
There currently isn't a way to write code in tests that is never visible to students unless the tests are hidden tests. Even if there was a way to make sure it wasn't displayed in the output in the notebook, it would still be readily available to students in the test file. The best way to implement this would be to hash the values and compare them to the known hash of the correct answer, e.g.

```python
h = hash(np.round(lowest_prime, 5)
assert h == <hash of correct_answer>
```
