### ISSUE TITLE
Best way to deal with timeouts?

### ISSUE THREAD

**Issue by terhorst** [ucbds-infra/otter-grader#469]
Thanks for releasing this software, it's really been helpful!

I'm wondering about the best way to deal with code that never returns? We currently have a problem set where the students are learning to use `while` loops. Inevitably, a number of submissions contain cells that fall into an infinite loop. Gradescope times out after 10m and returns an uninformative error message. It would be nice to be able a) tell them which question failed, and b) continue grading the other cells in the notebook. The only solution I have found is to wrap every call in something like [this](https://stackoverflow.com/questions/492519/timeout-on-a-function-call), but then the solutions contain a lot of extra complex code that the students don't understand. Is there a better way?

**Comment by chrispyles** [comment]
Currently Otter doesn't have a better way of handling this built-in. We have some controls in place when using Otter Grade (local Docker grading) that times out containers that run for too long, but it doesn't provide any useful information about the code that ran for too long, or even output a grade for the submission (much like Gradescope).
