### ISSUE TITLE
Otter Grade runs infinitely

### ISSUE THREAD

**Issue by asvattha** [ucbds-infra/otter-grader#470]
I followed the tutorial page closely. After running: 
otter grade -p submissions/ipynbs -a dist/autograder/demo-autograder_*.zip --pdfs -v

it runs the apt-get update infinitely. 

![Screenshot from 2022-01-14 15-57-57](https://user-images.githubusercontent.com/74628984/149592741-c24819ee-aa7d-4610-97d2-997b0dcb3778.png)

I had to cancel the job otherwise, it runs infinitely. 

**Expected behavior**
Should produce the  final_grades.csv and submission_pdfs files as mentioned in the tutorial. 

**Versions**
Python: 3.8.10
Otter: 3.2.1

**Comment by chrispyles** [comment]
I think this may be an issue specific to your machine. I've run the tutorial a few times today on mine (Mac w/ M1 processor) and had no issues. I don't think there's much I can do to help you debug this, unfortunately. Closing this issue out but please reopen it if you are able to confirm that this is an issue with Otter.
