### ISSUE TITLE
Save current notebook as part of `ottr::export()`

### ISSUE THREAD

**Issue by dbroockman** [ucbds-infra/otter-grader#474]
**Is your feature request related to a problem? Please describe.**
When students run `ottr::export()`, it creates a Zip file of the last saved version of the notebook, which might be out of date. Even though I tell students to manually save before running export, many forget to do so.

**Describe the solution you'd like**
When `ottr::export()` runs, have it save the current version of the notebook first.

**Describe alternatives you've considered**
I've told students to manually save first, but many forget.

**Additional context**
Many students then complain about their grades being wrong because the last answer or two doesn't show up.

**Comment by chrispyles** [comment]
Opened https://github.com/ucbds-infra/ottr/pull/20 which will be included in the next version of ottr.

**Comment by chrispyles** [comment]
This is included in ottr v1.4.0 which is on it's way to CRAN.
