### ISSUE TITLE
The tool for converting files to otter v1 doesn't successfully convert questions where tests have points assigned to them.

### ISSUE THREAD

**Issue by rohanjha123** [ucbds-infra/otter-grader#503]
**Describe the bug**
I'm using the following tool for upgrading otter: https://otter-grader.readthedocs.io/en/latest/otter_assign/index.html. The tool works fine in all cases, except for if a question in the otter v0 version had points assigned across different tests (e.g. points: -0 -1). In such cases, the tool fails to properly convert the question and assign points across all the different tests as specified.

**To Reproduce**
1. Make an otter v0 assignment with at least 1 question that has points assigned across different test cases.2. 
2. Try to use the CLI tool given on https://otter-grader.readthedocs.io/en/latest/otter_assign/index.html to convert the v0 assignment to v1.
3.  While the tool appears to work, after you run otter assign on the new document and attempt to work on the student version of the assignment, the otter grader cell for that question will bug out and throw a "points weren't assigned correctly" error.

Expected behavior**
I would expect the tool to work and the student version of the assignment to able to run the otter grader cell successfully.

**Versions**
This issue occurs while converting otter from v0 to v1 and my Python version is 3.8.8

**Additional context**
N/A

**Comment by chrispyles** [comment]
@rohanjha123 can you please share a notebook that reproduces this error?

**Comment by rohanjha123** [comment]
It should be reproducible by any notebook, but I'll send you a sample notebook via slack

**Comment by chrispyles** [comment]
I think this is actually an issue with Otter Assign, not with the converter. Otter Assign is not correctly trimming the list of point values in the student test file (it leaves the point values for hidden tests in).
