### ISSUE TITLE
PDF Generation Breaks Due to Outdated Packages

### ISSUE THREAD

**Issue by willfurtado** [ucbds-infra/otter-grader#514]
## Description
Data 8 has been encountering an issue with `otter` / Gradescope while trying to extract written work from otter submissions. It looks like there is an issue with the environment that is being used for autograding where the Docker image doesn't contain `pandoc` which causes an issue with `nbconvert`.

![Screen Shot 2022-08-23 at 12 45 54 PM (1)](https://user-images.githubusercontent.com/56857749/186282505-3aed61ad-d1f1-42d2-806f-89e68dabb885.png)

### Main Issues
1. `wkhtmltopdf` install is either outdated or non existent
2. `texlive` install had a deprecated dependency

### Temporary Fix
The temporary fix to get PDF generation working was to directly modify the `setup.sh` script within the `autograder.zip` automatically created by `otter`. The following changes were made:
1. Remove the lines: 
```bash
install wkhtmltopdf
wget --quiet -O /tmp/wkhtmltopdf.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
apt-get install -y /tmp/wkhtmltopdf.deb
```
2. Replace old package `texlive-generic-recommended` with `texlive-plain-generic`.

Our entirely new `setup.sh` is:
```bash
#!/usr/bin/env bash

if [ "${BASE_IMAGE}" != "ucbdsinfra/otter-grader" ]; then
    apt-get clean
    apt-get update
    apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgit2-dev texlive-lang-chinese

    # install conda
    wget -nv -O /autograder/source/miniconda_install.sh "https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh"
    chmod +x /autograder/source/miniconda_install.sh
    /autograder/source/miniconda_install.sh -b
    echo "export PATH=/root/miniconda3/bin:\$PATH" >> /root/.bashrc

    export PATH=/root/miniconda3/bin:$PATH
    export TAR="/bin/tar"
fi

# install dependencies with conda
conda env create -f /autograder/source/environment.yml

# set conda shell
conda init --all
```
## To Reproduce
Reproduction of this issue is likely difficult as Data 8 uses a custom script to compose assignments with `otter`. However, at the end of the day, it uses `otter assign` to create the `autograder.zip`. 

## Expected Behavior
A PDF, filtered by only the written questions, should be uploaded to the correct Gradescope assignment.

## Versions
Gradescope version: 3.1.4
Otter-Grader version: 3.3.0
Python version: 3.9.11

**Comment by chrispyles** [comment]
@willfurtado can you slack me some materials to reproduce this issue?
