### ISSUE TITLE
JN example for v4

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#515]
**Describe your inquiry** 

It should be extremely useful if an example Jupyter Notebook for v.4  with exception-based tests would be available, like [this one](https://github.com/ucbds-infra/otter-grader/blob/master/examples/data-88e-proj03/proj03.ipynb) for an older version.

**Comment by chrispyles** [comment]
The new notebook can be found at https://github.com/ucbds-infra/otter-grader/tree/master/examples/data-88e-proj03-exception
