### ISSUE TITLE
otter grade fails on grading tutorial

### ISSUE THREAD

**Issue by kirkmanne** [ucbds-infra/otter-grader#530]
**Describe the bug**
When following the tutorial instructions, otter grade fails to grade submissions.  This fails on both Mac and Winds using Docker.

**To Reproduce**
Follow the tutorial's directions.

**Expected behavior**
The tutorial should produce correct results.
 
**Versions**
Python 3.9.133 (From Anaconda download)
Otter 4.0.1

**Additional context**
tutorial % otter grade -v -p submissions/ipynbs -a dist/autograder/demo-autograder_2022_09_18T20_01_45_265574.zip -o output
Launching docker containers...
Grading submissions/ipynbs/demo-fails2.ipynb in container 5e28d18bff5a...
Grading submissions/ipynbs/demo.ipynb in container 51f6d3db5bc5...
Grading submissions/ipynbs/demo-fails1.ipynb in container 6347a06900f7...
Grading submissions/ipynbs/demo-fails3.ipynb in container 4a2be115ef58...
Grading submissions/ipynbs/demo-fails3Hidden.ipynb in container 6644c194fe22...
Grading submissions/ipynbs/demo-passesAll.ipynb in container 373b60de0619...
Traceback (most recent call last):
  File "/Users/kma/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(cli())
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/otter/cli.py", line 130, in grade_cli
    return grade(*args, **kwargs)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/otter/grade/__init__.py", line 64, in main
    grade_dfs = launch_grade(autograder,
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/otter/grade/containers.py", line 113, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/otter/grade/containers.py", line 113, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/Users/kma/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/kma/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/kma/opt/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kma/opt/anaconda3/lib/python3.9/site-packages/otter/grade/containers.py", line 189, in grade_assignments
    raise Exception(f"Executing '{submission_path}' in docker container failed! Exit code: {exit}")
Exception: Executing 'submissions/ipynbs/demo-fails1.ipynb' in docker container failed! Exit code: 1

**Comment by chrispyles** [comment]
@kirkmanne are you still experiencing this issue on the latest version of otter? if so can you run with the `-vv` flag and send the output?

**Comment by kirkmanne** [comment]
I was able to fix the problem by changing the setup to duplicate the setup
for non-ucbdsinfra/otter-grader images.

I changed setup.sh to:

#!/usr/bin/env bash

#if [ "${BASE_IMAGE}" != "ucbdsinfra/otter-grader" ]; then
    apt-get clean
    apt-get update
    apt-get install -y pandoc texlive-xetex texlive-fonts-recommended
texlive-plain-generic build-essential libcurl4-gnutls-dev libxml2-dev
libssl-dev libgit2-dev texlive-lang-chinese

    # install wkhtmltopdf
    wget --quiet -O /tmp/libssl1.1.deb
http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
    apt-get install -y /tmp/libssl1.1.deb
    wget --quiet -O /tmp/wkhtmltopdf.deb
https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
    apt-get install -y /tmp/wkhtmltopdf.deb

    # install conda
    wget -nv -O /autograder/source/miniconda_install.sh "
https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh"
    chmod +x /autograder/source/miniconda_install.sh
    /autograder/source/miniconda_install.sh -b
    echo "export PATH=/root/miniconda3/bin:\$PATH" >> /root/.bashrc

    export PATH=/root/miniconda3/bin:$PATH
    export TAR="/bin/tar"
#fi

# install dependencies with conda
conda env create -f /autograder/source/environment.yml

# set conda shell
conda init --all

Once I did that, the tutorial started working.

Kirk

**Comment by ColoMAX** [comment]
When modifying tutorial to use the zips instead (with -z), get similar behavior. 
Otter 4.4.1, Python 3.8.17, Ubuntu 22.04, Docker 24.0.4

**Comment by chrispyles** [comment]
@ColoMAX can you send the autograder zip file you generated and passed to the `otter grade` command?

**Comment by ColoMAX** [comment]
Found the problem. When running `otter grade -z ...` the `zips` option must logically also be true in the assignment config. But I am not certain why this should be the case, since the container can determine from the files in `/autograder/submission` whether to unpack first, instead of relying on the config.

**Comment by chrispyles** [comment]
Yeah, that was my suspicion.Uunfortunately it's required to be specified in both places currently (I think that's part of the instructions in the tutorial) but my goal is to remove that restriction in v5 of Otter (#395).
