### ISSUE TITLE
"Public tests" section  on gradescope show "Passed" even when tests are failing

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#539]
**Describe the bug**
The "Public tests" section on gradescope always shows up as "Passed", even when some of the tests fail:

![image](https://user-images.githubusercontent.com/4560057/194569199-b93880b4-97e1-4854-bc4d-87082d51d3bf.png)

In the stdout they always show up as NA for points, regardless how many points there are:

![image](https://user-images.githubusercontent.com/4560057/194569696-c4692f86-50f3-43a1-8286-32bc8d33241e.png)

**Expected behavior**

The headings does not show that everything passed when some public tests fail.

In general I think it would be good to remove this section if `show_hidden` is used in the metadata, because otherwise the info about these tests will show up twice, both under "Public" and then again under the question header, which can be confusing.

**Versions**

otter 4.0.2 python 3.9.13

**Additional context**

**Comment by chrispyles** [comment]
I think that the Public Tests section has always shown as passing since it's never had a point value assigned to it, but now that Gradescope lets you customize how it shows, I agree that showing it as failing when some public tests don't pass is a good idea.

w.r.t. not showing it if `show_hidden` is true, I think that it's fine to leave it shown as the default but make this behavior configurable, e.g. with a `show_public_summary` configuration. thoughts?

**Comment by joelostblom** [comment]
An option to control whether the public section is shown would be nice! I do think it makes more sense for the default to be to hide it if the tests are already showing up under their respective question heading as I don't see the value of seeing the same test in two places. I don't feel super strongly about that though and maybe I am missing something useful with seeing it twice?

**Comment by chrispyles** [comment]
The reason I think leaving it shown as the default is better is because `show_hidden` only makes the results of the hidden tests visible after grades are published, so not showing the public tests summary would mean that the student gets no feedback on their submission until grades are published.

**Comment by chrispyles** [comment]
Just merged #549 which fixes this bug and adds the `force_public_test_summary` configuration, which defaults to true. If you want to hide the public tests summary when `show_hidden` is true, set `force_public_test_summary` to false. This will be included in v4.1.0.

**Comment by joelostblom** [comment]
Awesome, thank for adding that so quickly!

> The reason I think leaving it shown as the default is better is because show_hidden only makes the results of the hidden tests visible after grades are published, so not showing the public tests summary would mean that the student gets no feedback on their submission until grades are published.

Ah ok that makes sense. I was thinking that students would always get this feedback locally in their own notebook, but I realize that it is possible to have a workflow where you design assignments that don't include those test cells in the notebook itself and they would have to view it on gradescope instead.

**Comment by chrispyles** [comment]
force_public_test_summary needs to be inside generate

**Comment by joelostblom** [comment]
Ah of course, it works now, thanks!
