### ISSUE TITLE
Update docs to clarify if python > 3.7 is fine

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#541]
**Describe your inquiry** 

In the example `environment.yml` file, the Python version is fixed at 3.7. Are we recommended to only use that version of Python with otter or can we use higher versions as well? Higher versions seem to work fine but I might be missing something. If higher versions are OK, could we update the template file to say `>=3.7`?

**Comment by chrispyles** [comment]
Otter should be compatible with Python 3.6+, but 3.7 is the default version for the grading image. #532 will make this version configurable by users (although still defaulting to 3.7) in otter v4.1.

**Comment by chrispyles** [comment]
I'm considering updating the default to 3.8 or 3.9 in otter v5, but that is a major change so I don't want to make it before another major release.

**Comment by joelostblom** [comment]
Thanks for the reply, I will keep `python=3.7` in the `environment.yml` file for now then.
