### ISSUE TITLE
Can all dependencies be specified in `environment.yml` or are the `requirements.txt/R` files required?

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#542]
**Describe your inquiry** 
From reading [the "Container Image" page in the docs](https://otter-grader.readthedocs.io/en/latest/workflow/otter_generate/container_image.html#environment-yml), it is not clear to me what is the difference between using the `requirements.txt/R` files versus specifying the package directly in the `environment.yml` file. Especially for R it is much faster to install e.g. `tidyverse` from conda than via `install.packages` since the latter will need to be built from source.

Can all dependencies be specified in `environment.yml` or are the `requirements.txt/R` files required?

**Comment by chrispyles** [comment]
Answered in #543
