### ISSUE TITLE
Make the base url for authenticating with gradescope configurable

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#555]
**Is your feature request related to a problem? Please describe.**
After manually changing this line to `.ca` instead of `.com`, my credentials work.

https://github.com/ucbds-infra/otter-grader/blob/d299fd20d78e693dc198b72b4a685b5b3d9cad2d/otter/generate/token.py#L7

**Describe the solution you'd like**
An option in the assignment config for the base url next to the token and IDs.

**Comment by chrispyles** [comment]
@joelostblom are you using Otter's PDF upload functionality? If so are you also running into issues with using the default URL to upload submissions using Gradescope's API, or is it just for authenticating to retrieve your token?

**Comment by joelostblom** [comment]
I was using this only to get the token, but I no longer personally have a need for it since the PDF can't be automatically posted to the same assignment (I'm asking students to manually upload a PDF instead)

**Comment by chrispyles** [comment]
I think what we can do is check for an environment variable e.g. `OTTER_GRADESCOPE_BASE_URL` and use its value if present and otherwise default to `https://www.gradescope.com`. What are your thoughts on this solution @joelostblom?

**Comment by joelostblom** [comment]
Yeah, I think that could be a viable solution. However, as I mentioned above, I no longer have a need for this personally and since no one else have commented on this issue, maybe it is not worth putting development time towards?

**Comment by chrispyles** [comment]
That's a good point. I'll leave this here as a potential solution that can be implemented if it becomes needed in the future. For now, will close this issue.
