### ISSUE TITLE
Can I create an assignment with a different version of otter than what students have installed 

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#557]
**Describe your inquiry** 
I would like to install Otter 4.1.0 to use some of the new options, but all students in my course already have 4.0.2 installed. I am thinking this would probably be fine but I wanted to double check whether there is any requirement that otter assignments are run with the exact same version they were created with to avoid issues?

**Comment by chrispyles** [comment]
I don't think it should cause any issues; the jump from v4.0.2 to v4.1.0 didn't affect any of the Otter Check code.
