### ISSUE TITLE
"variable not found" for some tests with `otter grade` but `otter run` works fine

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#558]
**Describe your inquiry** 
Sorry for the many issues lately, let me know if I'm causing too much noise and I can dial it back. I am experiencing a somewhat odd issue where a student notebook is passing all the public tests both in the notebook directly and if I grade using `otter run` locally. However, if I grade in the container via `otter grade` or on gradescope, two of the questions fail with `NameError: name 'variable_name' is not defined` and are assigned score 0. The variable is clearly defined in their notebook, and the autograder manages to find the variable names for all other questions before and after these two. I am at a bit of a loss at what could be wrong here, would you happen to have any pointers to what might be the underlying cause? This is with 4.1.0, and it is currently only happening to 1/20 students (but that student is the most recent submission, so not sure if it is related, I retriggered autograding for all, but still the same result).

Full traceback in case it is helpful:

```
q9 results:
    q9 - 1 result:
        ❌ Test case failed
        Trying:
            assert bars_co2 is not None, "Your answer does not exist. Have you passed in the correct variable?"
        Expecting nothing
        **********************************************************************
        Line 1, in q9 0
        Failed example:
            assert bars_co2 is not None, "Your answer does not exist. Have you passed in the correct variable?"
        Exception raised:
            Traceback (most recent call last):
              File "/root/miniconda3/envs/otter-env/lib/python3.7/doctest.py", line 1337, in __run
                compileflags, 1), test.globs)
              File "<doctest q9 0[0]>", line 1, in <module>
                assert bars_co2 is not None, "Your answer does not exist. Have you passed in the correct variable?"
            NameError: name 'bars_co2' is not defined
        Trying:
            assert type(bars_co2) == type(alt.Chart()), "Your answer is not an altair Chart object. Check to make sure that you have assigned an alt.Chart object."
        Expecting nothing
        **********************************************************************
        Line 2, in q9 0
        Failed example:
            assert type(bars_co2) == type(alt.Chart()), "Your answer is not an altair Chart object. Check to make sure that you have assigned an alt.Chart object."
        Exception raised:
            Traceback (most recent call last):
              File "/root/miniconda3/envs/otter-env/lib/python3.7/doctest.py", line 1337, in __run
                compileflags, 1), test.globs)
              File "<doctest q9 0[1]>", line 1, in <module>
                assert type(bars_co2) == type(alt.Chart()), "Your answer is not an altair Chart object. Check to make sure that you have assigned an alt.Chart object."
            NameError: name 'bars_co2' is not defined
```

Notebook code and passed public test:

![image](https://user-images.githubusercontent.com/4560057/195635341-f49b7ffc-0c7c-4496-a61d-ee2e1c898a93.png)

**Comment by chrispyles** [comment]
@joelostblom can you try running on Gradescope in debug mode? To do this, use their debug via SSH feature to SSH into the container, add `"debug": true` in `/autograder/source/otter_config.json`, and run `/autograder/run_autograder`. (Debug mode prevents Otter from swallowing errors, so if there's an error being thrown in the cell that prevents `bars_co2` from being defined, it will be raised instead of being ignored.)

**Comment by chrispyles** [comment]
(If you prefer, you can also do this locally by setting the same key in your `otter_config.json`, re-zipping your autograder config zip, and using `otter grade` with the `-vv` flag.)

**Comment by joelostblom** [comment]
Thanks for the instructions for how to run in debug mode! Turns out it was a difference between the minor pandas version on the autograder that caused the issue so closing this.
