### ISSUE TITLE
reading data from a csv

### ISSUE THREAD

**Issue by jake-bobowski** [ucbds-infra/otter-grader#559]
Dear Otter-Grader,

My name is Jake Bobowski from the University of British Columbia.  Thank you very much for creating and distributing Otter-Grader!

We are planning to use Otter-Grader in our first-year physics course starting in January 2023.  We will write the lab manuals for the course using Jupyter Notebooks (using Python).  Parts of the student submissions will be auto-graded using Otter-Grader.  We are planning to have students enter their data into csv files that are then imported into the Jupyter Notebook and displayed in a spreadsheet-like environment.  

To be brief, I have two questions about what Otter-Grader can and cannot do:

1.	If students have a csv file in the same directory as their ipynb file, is it possible to have grader.export() to place the csv file into the zip that contains the ipynb file and the pdf file containing any material marked from manual grading?
2.	Can Otter-Grader then use the data in the csv files to run the tests and complete the auto grading?  Each student would have a unique set of data and, therefore, a unique csv file.

Thanks in advance for your help!

Jake

**Comment by chrispyles** [comment]
> 1. If students have a csv file in the same directory as their ipynb file, is it possible to have grader.export() to place the csv file into the zip that contains the ipynb file and the pdf file containing any material marked from manual grading?

Yes, this is possible. Take a look at the `files` argument of [`otter.Notebook.export`](https://github.com/ucbds-infra/otter-grader/blob/master/otter/check/notebook.py#L325). If you're using Otter Assign, it's not currently possible to set this argument in the export cell it generates, so you'll need to make that change by hand.

> 2. Can Otter-Grader then use the data in the csv files to run the tests and complete the auto grading? Each student would have a unique set of data and, therefore, a unique csv file.

Yes, all files in the zip file are placed into the same directory as the submission notebook, so the code should be able to access them as long as they use relative (not absolute) paths.
