### ISSUE TITLE
Make `force_public_test_summary: false` only apply after the submission deadline

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#561]
**Is your feature request related to a problem? Please describe.**
Follow up from #549 #539, a few of my students commented on that it is nice to see the public tests upon submission to know they didn't submit the wrong file by accident, which I think is a valid point.

**Describe the solution you'd like**
 Ideally the `force_public_test_summary` option would only apply after the submission deadline once the `show_hidden` key goes into effect and all the public tests are printed under their respective question heading in the output.

**Comment by chrispyles** [comment]
I don't think Gradescope has a test case visibility setting that goes away after grades are published; the available visibility settings are listed [here](https://gradescope-autograders.readthedocs.io/en/latest/specs/#controlling-test-case-visibility). I think you would need to submit a feature request to Gradescope to add this visibility setting, and then reopen this issue so Otter can make use of it.

(The only other way of doing it would be to require the instructor to re-run the autograder for every submission just after the due date has passed, and compare the current date to the due date in the autograder to determine whether that test case should be added to the output, but I don't like this solution.)
