### ISSUE TITLE
Show assignment summary/overview when running `otter assign`

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#564]
**Is your feature request related to a problem? Please describe.**
I find myself often looking for an easy overview of how many questions I have created and how many points I have assigned to each. Especially as I use different kinds of questions (e.g. practice, regular, challenging, extra-credit, etc) it becomes difficult to flip through the notebook to overview how the points are allocated.

**Describe the solution you'd like**
It would be great if a summary of the questions and their points were printed at the end of running `otter assign` so that it was easy to overview the structure of the assignment we just created. I am thinking something like this:

```
Total Points: 32
Autograder:   26
Manual:        6

           name    points
1           q1        2.0
2           q2        2.0
2           q3        2.0 (manual)
2           q4        2.0
3           q5        3.0
4           q6        4.0
5           q7        4.0 (manual)
6           q8        6.0
7           q9        1.0
8           q10       6.0
```

It is currently possible to get something similar with `otter run` but it doesn't include manually graded questions

**Comment by chrispyles** [comment]
Added this with #664. To see the summary, you will need to use the `-v` flag of Otter Assign.

**Comment by joelostblom** [comment]
Awesome, thank you!
