### ISSUE TITLE
Allow for centralized configuration

### ISSUE THREAD

**Issue by afeld** [ucbds-infra/otter-grader#565]
**Is your feature request related to a problem? Please describe.**

I have separate notebooks for each assignment, but they are generally structured the same. This means copying [configuration options](https://otter-grader.readthedocs.io/en/latest/otter_assign/v1/notebook_format.html#assignment-config) across all of them.

**Describe the solution you'd like**

I'd like to be able to specify configuration options in a single place, ideally in a config file. CLI arguments would work as well.

**Describe alternatives you've considered**

The documentation references `otter_config.json`, which may solve this problem, but I'm not seeing any documentation about the possible values of that file.

**Additional context**

https://github.com/ucbds-infra/otter-grader/issues/395 may be related.

**Comment by chrispyles** [comment]
Documentation for the keys available in `otter_config.json` can be found [here](https://otter-grader.readthedocs.io/en/latest/workflow/otter_generate/index.html#grading-configurations) but I don't think this will do what you want -- this is a file generated by Otter Assign based on the configurations in your assignment config. I think allowing this to be specified in a separate file is a good idea.

**Comment by chrispyles** [comment]
Support for these files was implemented in #573. To use this functionality, specify a `config_file` in your assignment config:

```yaml
# ASSIGNMENT CONFIG
config_file: assignment_config.yml
```
