### ISSUE TITLE
Make gspread an optional dependency?

### ISSUE THREAD

**Issue by yuvipanda** [ucbds-infra/otter-grader#577]
When trying to install otter-grader via conda-forge on jupyterlite (so users don't have to install it manually), we run into this error: https://github.com/yuvipanda/materials-x22/actions/runs/3389289740/jobs/5632226075

```
To activate this environment, use

     $ mamba activate /tmp/xeus-python-kernel/envs/xeus-python-kernel

To deactivate an active environment, use

     $ mamba deactivate

conda-forge/noarch                                          Using cache

Looking for: ['python=3.10', 'xeus-python', 'pandas', 'matplotlib', 'ipympl', 'datascience', 'otter-grader']

Encountered problems while solving:
  - nothing provides googleapis-common-protos >=1.6.0,<2.0dev needed by google-api-core-1.22.3-pyh9f0ad1d_0

[LiteBuildApp] ERROR | [lite] [post_build] [jupyterlite-xeus-python] [ERR] Command '['mamba', 'install', '--yes', '--prefix', PosixPath('/tmp/xeus-python-kernel/envs/xeus-python-kernel'), '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'https://repo.mamba.pm/conda-forge', 'python=3.10', 'xeus-python', 'pandas', 'matplotlib', 'ipympl', 'datascience', 'otter-grader']' returned non-zero exit status 1.
```

I *think* this is because `googleapis-common-protos` is a compiled dependency? And probably deeper down a dependency of gspread.

Would be nice to make it optional, so we can ship by default with JupyterLite

**Comment by chrispyles** [comment]
I wonder why this is happening. I'm able to install otter-grader without incident on Jupyterlite with the `%pip` magic

```
%pip install otter-grader
```

**Comment by chrispyles** [comment]
`googleapis-common-protos` does appear to be in conda-forge: https://anaconda.org/conda-forge/googleapis-common-protos

**Comment by yuvipanda** [comment]
@chrispyles on conda-forge, the protos package is not a noarch package - it contains compiled code. Hence it can’t be installed on jupyterlite as is. Packages without compiled code are marked as noarch.

not sure why this works with pip though!

**Comment by sean-morris** [comment]
@yuvipanda and @chrispyles I am still running into problems building otter-grader into a jupyter-lite instance.

I am not sure I am correct here but it looks to me that while the 4.2.1 version for otter-grader has removed gspread from the requirements.txt(now in requirements-test.txt) the conda package is not the same.

I ran: 
conda search otter-grader==4.2.1 --info

and got:
Loading channels: done
otter-grader 4.2.1 pyhd8ed1ab_0
-------------------------------
file name   : otter-grader-4.2.1-pyhd8ed1ab_0.conda
name        : otter-grader
version     : 4.2.1
build       : pyhd8ed1ab_0
build number: 0
size        : 105 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/otter-grader-4.2.1-pyhd8ed1ab_0.conda
md5         : d08670acde56b3d283db53a456718adc
timestamp   : 2022-12-17 20:37:26 UTC
dependencies: 
  - click
  - dill
  - fica >=0.2.0
  - google-api-python-client
  - google-auth-oauthlib
  - gspread
  - ipython
  - jinja2
  - jupytext
  - nbformat
  - pandas
  - python >=3.8
  - python-on-whales
  - pyyaml
  - requests
  - six
  - wrapt

It is still a little unclear to me how we know gspread is the problem but I will defer to @yuvipanda here.

**Comment by chrispyles** [comment]
Should be fixed by https://github.com/conda-forge/otter-grader-feedstock/pull/4
