### ISSUE TITLE
`grade_submission` in `for` loop hangs

### ISSUE THREAD

**Issue by spring-haru** [ucbds-infra/otter-grader#580]
**Describe the bug**
I am not sure whether it is a bug or an expected outcome. 
I tried to use `grade_submission()` in `for` loop in the following code, but it hangs after grading 4 or 5 `.ipynb` files apparantly at `grade_submission()`.
(The reason for using the code is because Docker was extremely slow (or hangs) in grading with AMD64 warnings in all active containers in my M1 MacBookPro.)
```
import os
import pandas as pd
from otter.api import grade_submission

pwd = os.getcwd()
zip_file = "./dist/autograder/my_autograder.zip"
directory = 'submissions'

score_dic = {}

for filename in os.listdir( os.path.join(pwd,directory) ):

    if filename.endswith('.ipynb'):
        
        res = grade_submission(f'./{directory}/{filename}', zip_file, quiet=True)
        
        q_list = res.test_files
        
        score_list = []
        
        for q in q_list:
            
            score_list.append( res.get_score(q) )        

        score_dic[filename] = score_list

pd.DataFrame(score_dic, index=q_list).T.reset_index().to_csv(f'my_grade_file.csv')
```

**To Reproduce**
1. Run the code in Terminal with appropriate files like `.ipynb` and `.zip`.

**Expected behavior**
Hopefully, it creates a `.csv` file with grades.

**Versions**
otter-grader v4.2.0

**Additional context**
I tried the following `python -m trace --trace my_grading_file.py`, and it always stops at
```
 --- modulename: contextlib, funcname: __enter__
contextlib.py(312):         self._old_targets.append(getattr(sys, self._stream))
contextlib.py(313):         setattr(sys, self._stream, self._new_target)
```

**Comment by chrispyles** [comment]
@spring-haru can you provide more of the `trace` output so I can determine where in Otter this context is being entered?

**Comment by spring-haru** [comment]
@chrispyles I have found the reason. It is NOT caused by `otter`, but infinite loops some students wrote. I wonder if there is an option for an execution time period of each submission. If not, it might be useful to introduce it.

**Comment by chrispyles** [comment]
It is possible to do this with `otter grade` (i.e. grading in a Docker container) but not with `otter.api.grade_submission`. Adding a timeout functionality that works cross-platform would require introducing multithreading to this part of the code, which I'm hesitant to do, but it should be trivial to write a wrapper for your own grading code that at least prevents your code from hanging, although it won't be able to provide partial credit.

**Comment by spring-haru** [comment]
Thanks for pointing out an execution time option, which I believe is `--timeout` for `otter grade`. I usually use Docker for grading, and I will use it next time.
