### ISSUE TITLE
Raise expclicit warning when using files not included in the the `files` metadata

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#585]
**Describe the bug**
Consider this example notebook [test_otter.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/10057334/test_otter.ipynb.txt):

![image](https://user-images.githubusercontent.com/4560057/203079972-7a18a122-3997-4ae4-9de9-dfa1880ffc63.png)

If I run `otter assign test_otter.ipynb ./`, I will get the following error message:

```
    q1 results:
        q1 - 1 result:
            ❌ Test case failed
            Trying:
                assert y is not None
            Expecting nothing
            **********************************************************************
            Line 1, in q1 0
            Failed example:
                assert y is not None
            Exception raised:
                Traceback (most recent call last):
                  File "/home/joel/miniconda3/envs/573/lib/python3.10/doctest.py", line 1350, in __run
                    exec(compile(example.source, filename, "single",
                  File "<doctest q1 0[0]>", line 1, in <module>
                    assert y is not None
                NameError: name 'y' is not defined
```

`y` is clearly defined here, and it is really quite cryptic to understand what is going on, especially in larger notebooks. I spent a few hours stuck on this and trying to reinstall otter as well as re-writing my code. It turns out that although the file `data/tweets.csv` exists in that location and runs fine in when doing "Restart and run all" in JupyterLab, it will fail silently when running `otter assign` causing all the following lines in that cell to not be executed. In the example above that means that `x` is never defined, which make it impossible to define `y`. 

**To Reproduce**
Run otter assigned on the attached notebook

**Expected behavior**
The solution was to add `- data` to the yaml `files` section, which makes sense, but there should be a warning raised by otter saying exactly this instead of failing silently and raising warning later that leads the user astray as to what to troubleshoot.

**Versions**
Otter 4.2.0, Python 3.10.x

**Additional context**

**Comment by chrispyles** [comment]
To a certain extent, we already have this functionality. The `--debug` flag of `otter assign` will cause any errors raised while running the notebook to be thrown instead of swallowed, so in this example it should've raised the `FileNotFoundError` and stopped executing when you tried to read the file in with `pd.read_csv`. We recommend using the `--debug` flag as a normal part of your debugging workflow for errors like this. Given that we already have a way of surfacing this information and impracticality of adding a way of parsing the code to find all of these file paths and generate warnings for them, I'm going to close this issue.

**Comment by joelostblom** [comment]
Thanks for the reply Chris, I think one of the tricky things here is that there is already an error thrown here, namely `NameError: name 'y' is not defined`. The immediate thought when seeing an error like this is that something is wrong with the definition of `y` and I don't think it is easy to understand that that there is a flag that would change which error comes up. My course of action in this case would be to troubleshoot the error I'm seeing rather than looking for another one.

I hear what you are saying the the `--debug` flag already offers the functionality, but maybe it could be made more discoverable? For example, do you think there could be some generic text appended to error message to hint to people that there could be other invisible errors causing the surfaced error? Something like this maybe:

```
NameError: name 'y' is not defined

There might other underlying errors that are not printed. Use the --debug flag to show all errors.
```
