### ISSUE TITLE
Make `# SOLUTION` compatible with multi-line assignment

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#588]
**Is your feature request related to a problem? Please describe.**
It would be convenient if `# SOLUTION` tags would work when the assigned expression is split over multiple lines. e.g.

```
x = {  # SOLUTION
    'one': 1,
    'two': 2
}
```

which currently becomes:

```
x = ...
    'one': 1,
    'two': 2
}
```

**Describe the solution you'd like**
I would like the output of the above to be:

```
x = ...
```

**Describe alternatives you've considered**
I am currently doing this which works but is a bit more typing:

```
x = {  # SOLUTION
# BEGIN SOLUTION NO PROMPT
    'one': 1,
    'two': 2
}
# END SOLUTION
```

**Comment by chrispyles** [comment]
Since all of Otter's solution parsing uses regex, it would be somewhat challenging to handle multiline solutions with just the `# SOLUTION` comment. The recommended way to achieve this behavior is either the one you describe above or to use a custom prompt:

```python
""" # BEGIN PROMPT
x = ...
""" # END PROMPT
# BEGIN SOLUTION NO PROMPT
x = {
}
# END SOLUTION
```
