### ISSUE TITLE
Can't create raw cells in Deepnote/Colab

### ISSUE THREAD

**Issue by surajrampure** [ucbds-infra/otter-grader#592]
From an instructor that filled out the Otter-Grader Adoption Survey:

> One pain point of Otter is that it requires using Raw cells for denoting start/end of sections. Some notebook tools (Deepnote, Colab, etc) don't allow for the creation of Raw cells, which makes authoring notebooks using Otter v1 impossible.

**Comment by chrispyles** [comment]
Potential solution: as an alternative to raw cells, allow users to put what would normally be in a raw cell in a markdown code block with `otter` as the language name:

````markdown
```otter
# BEGIN ASSIGNMENT
files:
    - data.csv
```
````
