### ISSUE TITLE
Executing otter-grader v4.2.1 for RMD files fails to generate different versions (student, grader) of the RMD master file

### ISSUE THREAD

**Issue by opterix** [ucbds-infra/otter-grader#596]
**Describe the bug**
Executing the [ottr-sample](https://github.com/ucbds-infra/ottr-sample) with a new otter installation v.4.0. After executing the following command in console:
`otter assign hw01.Rmd dist`

with otter v4.2.1 the process is executed silently without any errors (even with --verbose and --debug flags). However the resulting Rmd files are the same. No extraction of the R blocks and otter-grader instructions is performed in any of the versions

**To Reproduce**
1. Install otter-grader v4.2.1
2. Download the otter-sample directory
3. Execute `otter assign hw01.Rmd dist` in the otter-sample directory
4. There is no difference between ./dist/autograder/hw01.Rmd and ./dist/student/hw01.Rmd

**Expected behavior**
If there is any problem converting the RMD file, the execution of the command should point out any error.

**Versions**
python = 3.8.5
otter-grader = 4.2.1

**Additional context**
I downgraded the otter-grader to v3.3.0, and the parsing of the RMD document is working fine

**Comment by chrispyles** [comment]
Sorry- forgot to update that repo after I changed the Rmd format. Should be fixed as of https://github.com/ucbds-infra/ottr-sample/commit/01560500457f216f57d81766237736adc04d56eb.
