### ISSUE TITLE
PyPDF2 version 3.0.0 and above throws DepracationError

### ISSUE THREAD

**Issue by dbroockman** [ucbds-infra/otter-grader#603]
**Describe the bug**
When running `otter assign` I get the following error: `PyPDF2.errors.DeprecationError: PdfFileMerger is deprecated and was removed in PyPDF2 3.0.0. Use PdfMerger instead.`

**Versions**
Otter version 4.3.0
PyPDF2 version 3.0.1

**Comment by chrispyles** [comment]
v5.0.0 will convert from PyPDF2 to pypdf.
