### ISSUE TITLE
Don't remove lines with cell magic

### ISSUE THREAD

**Issue by rohanjha123** [ucbds-infra/otter-grader#604]
**Is your feature request related to a problem? Please describe.**
Currently, lines with cell magic are [removed](https://otter-grader.readthedocs.io/en/latest/execution.html?highlight=%25%20magic#notebooks) when parsing a notebook. Data 100 would love to use cell magic to autograde SQL assignments (using ipython-sql) and xarray questions. Please see the following [slack thread](https://uctech.slack.com/archives/CC3NKQA3B/p1675636560659309) for Fernando Perez's thoughts.

**Describe the solution you'd like**
I would love it if cell magic wasn't removed and instead could be autograded like any other cell.

**Describe alternatives you've considered**
[Data 101](https://github.com/cal-data-eng/fa22/blob/main/proj/proj1/proj1.ipynb) currently uses cell magic for questions and has their students either manually generate csv’s or copy paste the results into another cell right below it. They then grade the csv's and/or manually copied results. This approach feels a bit hacky and for ~1200 students with limited programming experience like in data 100, I can see students running into all sorts of bugs. 

**Additional context**
This has been a desire of various instructors for a few semesters now (at least since Spring 2022); I'm finally filing the request.

**Comment by fperez** [comment]
Thanks @rohanjha123 for opening this issue! I'm happy to provide further input to the otter team as needed.

**Comment by chrispyles** [comment]
This is currently on the roadmap for v5. I'm working on a PR to change Otter's execution internals to use nbconvert's `ExecutePreprocessor` to execute the notebook, which will support all of these IPython magic features, instead of Python's `exec` function.

**Comment by fperez** [comment]
Wonderful, very glad to hear this!
