### ISSUE TITLE
Does otter-grader support MyST Markdown?

### ISSUE THREAD

**Issue by westurner** [ucbds-infra/otter-grader#606]
docs/index.rst (but not README.rst) says that otter-grader supports RMarkdown, but does not mention MyST Markdown. Does otter-grader support MyST Markdown?

- https://github.com/ucbds-infra/otter-grader/search?q=myst+markdown
- https://www.google.com/search?q=otter-grader+myst-markdown

**Comment by chrispyles** [comment]
Are you asking about Markdown flavors supported by Otter Export? Or what types of files Otter can grade?

**Comment by chrispyles** [comment]
Closing this issue as it hasn't been updated in a while but please feel free to reopen if you require more information or reach out on the Slack.
