### ISSUE TITLE
Old version of libssl generates error with gradescope 22.04 container

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#608]
**Describe the bug**
Installing in a gradescope Ubuntu 22.04 container generates an error due to libssl1.1 not being available to install (there is also an error about texlive):

```
...
Fetched 110 kB in 0s (232 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package texlive-generic-recommended
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wkhtmltox : Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
...
```

**To Reproduce**
Setting up a new container on gradescope with ubuntu 22.04.

**Expected behavior**
The installation continues after this error, but it would be nice to upgrade to libssl3 in `setup.sh` [which is what is available for Ubuntu 22.04](https://askubuntu.com/questions/1408000/unable-to-locate-package-libssl1-1) to avoid the error.

**Versions**
4.1.2

**Comment by chrispyles** [comment]
@joelostblom are you still getting this error on the latest versions of Otter? Can you send me an autograder zip file in Slack that reproduces it?

**Comment by chrispyles** [comment]
Closing this issue as there haven't been any updates. Please feel free to reopen if this is still an issue.
