### ISSUE TITLE
Examples of how to use Otter grader with GitHub classrooms or GitHub actions

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#613]
**Describe your inquiry** 
I wonder if there are any examples of how otter grading could be done on notebooks uploaded to GitHub repositories. The grading could be either via GitHub classrooms or GitHub actions, and would ideally involve pusing grades to Canvas (but that's not necessary). I have seen the [github classroom docs for testing](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/use-autograding), but it would love to see a working example for this using Otter, either a template or an existing course.

**Comment by chrispyles** [comment]
I'm not aware of any existing classes or examples of using Otter with GH actions/classrooms, but I'd imagine it would be relatively simple to set up. You could just write an action that installs otter and uses `otter run` to grade the assignment. The challenge is maintaining the security of hidden tests (if the assignment has hidden tests) as the autograder zip would need to be located somewhere that the action can access it (likely in the students' repos) which means students would also be able to access it and see the hidden tests.

The best approach I can think of for solving this would be to create two autograder zips, one with hidden tests and one without (this can be done manually by copying the one otter produces and removing the all hidden test cases from the `tests` directory inside it). Then the workflow would look something like this:

1. Create student repos with the GH action and the autograder zip without hidden tests.
2. Distribute repos to students. While working on the assignment, students can use the GH action as CI to check their solutions as they work on them.
3. After due date, fork all student repos and ensure students can't view the forks. In each fork, replace autograder zip with the copy that includes hidden tests.
4. Run GH action again on all repos and collect results for grades.

I hope this helps.
