### ISSUE TITLE
Show total points together with tests in `grader.check_all()`

### ISSUE THREAD

**Issue by joelostblom** [ucbds-infra/otter-grader#614]
**Is your feature request related to a problem? Please describe.**
It would be useful if `grader.check_all()` also showed the number of points the student got in total on the assignment. Currently it only shows which tests are passing and failing, but since tests might have different point values it is hard to get an overall picture of how well they did.

![image](https://user-images.githubusercontent.com/4560057/222604095-6129b41a-28d3-4918-ad4d-482f1c1a8370.png)

**Comment by chrispyles** [comment]
I'm hesitant to add this as students will be running this function as they work through the assignment when they only have public tests available to them. If we show students a point value here but that point value changes during grading once hidden tests are factored in, this will create a lot of confusion.
