### ISSUE TITLE
Can parts of the grader.check() output be hidden without hiding the entire test?

### ISSUE THREAD

**Issue by jake-bobowski** [ucbds-infra/otter-grader#616]
Is it possible to hide parts of the output from grader.check() and display only a custom failure_message?

Here is screenshot of an example configuration notebook:

![image](https://user-images.githubusercontent.com/82606543/223496133-217160c3-ac33-470f-9eb4-985b2509d073.png)

There is a single multiple-choice question and students should enter 'a' as the answer.  Here's what students see in their notebooks when entering a valid, but incorrect response.

![image](https://user-images.githubusercontent.com/82606543/223496491-44694895-ccd0-4d17-9a89-78f8dd65cfc1.png)

I've set a custom failure_message that, in this case, says "Please try again".  The output of grader.check() reveals the correct answer by displaying "a1_1.lower() == 'a'".  Is it possible to hide parts of this output while displaying only the custom failure_message?  I'd like students to know that they've entered an incorrect response without revealing the correct answer.  In this toy example, the failure_message is not useful, but it could be setup to provide valuable feedback/hints in a real-life example.

Thanks!

Jake
@Jaymes92 @jake-bobowski

**Comment by joelostblom** [comment]
I think this would be very useful as well and I started this work in #536, but won't have time to pick that up in another few months unfortunately. Help welcome!

**Comment by aaronsmoore** [comment]
A temporary workaround that I've been using has been hashing the multiple choice answers so students only see a hashed version of the answer like this:

![D62F010D-EC85-4B2E-8D70-8B138E1A7B36](https://user-images.githubusercontent.com/73104085/224153862-665a504a-465c-4a48-a616-da37404b0db0.jpeg)

Not sure this is what you're looking for but I can send more details if you're interested.

**Comment by jake-bobowski** [comment]
Thanks @aaronsmoore, that looks great!  I would definitely be interested in seeing the details.

**Comment by aaronsmoore** [comment]
All credit to the D102 team for this method.

You'll use the following function to hash students' answers.
```python
import hashlib

def get_hash(num):
    """Helper function for assessing correctness"""
    return hashlib.md5(str(num).encode()).hexdigest()
```

The general workflow looks something like this.

![image](https://user-images.githubusercontent.com/73104085/224433076-973e0b27-08f0-49d3-b610-c9681a81cf94.png)

There are some other considerations for multiple-answer questions such as sorting the student answer list/numpy array so it lines up with the hashed answer.

Let me know if you have any questions about this.

**Comment by jake-bobowski** [comment]
Hi @aaronsmoore, Thanks so much for the suggestion.  It was really helpful and easy to implement.  Here's an example use from our first-year physics course:

![image](https://user-images.githubusercontent.com/82606543/224446987-c7166c1d-9126-4ac6-a9b1-d56686a85f8a.png)

**Comment by chrispyles** [comment]
I hope the hashing solution temporarily helps with this issue @jake-bobowski. Since this seems like the same ask as #419, I'm going to de-dupe it in favor of that one.
