### ISSUE TITLE
Blacklist zip file name in autograder settings

### ISSUE THREAD

**Issue by dbroockman** [ucbds-infra/otter-grader#617]
**Is your feature request related to a problem? Please describe.**
When my GSIs grade assignments with open-ended questions, Gradescope will auto-scroll to the same part of the assignment when only an .ipynb file is uploaded. However, if students export assignments using the `ottr::export` box, a .zip is exported which they upload. This .zip functionality is very useful because it prevents other browser errors. However, when students upload a .zip file, Gradescope then shows two files in the autograder window,  a `__zip filename__` file and the .ipynb notebook itself. The presence of two files prevents the auto-scrolling from working.

**Describe the solution you'd like**
I e-mailed Gradescope about this issue. They said the solution was as follows: "If you don't want to see the zip file name, you can always blacklist it on your autograder settings, so that it's not stored in the repository."

**Describe alternatives you've considered**
Students could upload the .ipynb directly, but on many machines and browsers the .ipynb doesn't download well (e.g., Chrome opens it in a separate window and appends .json).

**Comment by chrispyles** [comment]
I wasn't previously aware of this feature, but I think this is something you need to configured on Gradescope. I see this in the assignment settings for an autograded assignment:

![Screenshot 2023-06-25 at 12 52 31 PM](https://github.com/ucbds-infra/otter-grader/assets/40970945/7b7a0fe5-309d-4c07-8a46-b60153d5c8b8)

I think just adding `__zip_filename__` to this setting should work.
