### ISSUE TITLE
Add files arguments pass in at # ASSIGNMENT CONFIG to Export Cell

### ISSUE THREAD

**Issue by scott-yj-yang** [ucbds-infra/otter-grader#620]
**Is your feature request related to a problem? Please describe.**

I found the zipping students' submission feature by `grader.export()` pretty useful. We aim to combine the written LaTeX questions along with the coding question in a single notebook. In order to support students who are not familiar with LaTeX, we want them to insert images into the markdown cell.

**Issue:**
The images are not automatically compressed into the zip file as those are not specified by the `grader.export(files=)` arguments. In addition, in the student version of the notebook, we cannot easily pass on the argument of `files` by the assignment config at the top of the notebook. Plus, the support of passing directories instead of specific file paths.

**Describe the solution you'd like**
Add argument support under `export_cell, files` and pass that to the `grader.export(files=files)`. This should include all the subfiles in the specified directory.

**Comment by chrispyles** [comment]
Hi @scott-yj-yang, thanks for the issue. This is actually _supposed_ to be currently supported (there is an `export_cell: files:` key in the assignment config and it does accept directories) but it looks like the implementation of `Notebook.export` w.r.t. globbing files in directories is broken. I will open a PR to fix that which will be included in v5.1.0.
