### ISSUE TITLE
Otter assign slowdown on long variable names

### ISSUE THREAD

**Issue by stephenfreund** [ucbds-infra/otter-grader#634]
**Describe the bug**

Long variable names in Python notebooks can cause what appears to be an exponential slowdown in `otter assign`.

**To Reproduce**

1. Run `otter assign v1.ipynb .` on the attached notebook.  It contains the following source line inside a question's solution block:

    ```
    this_is_a_long_variable_name = 0
    ```

    On my computer, `otter assign` takes ~40 seconds to complete.

2. Change that source line to

    ```
    this_is_a_long_variable_name12 = 0
    ```

    and it will take about four times that long (~160 seconds).

**Versions**
Python version: 3.9.15
Otter-Grader version: 4.3.2

**Additional context**

The behavior appears to be rooted in this [line from `solution.py`](https://github.com/ucbds-infra/otter-grader/blob/002f94136e7bcbfe1900d2c0e7f859990543b278/otter/assign/solutions.py#L55):

```
solution_assignment_regex = re.compile(r"(\s*(?:[\w.]+(?:\[['\"].*['\"]\])*(?:,\s*)?)+\s*=).* ?# ?SOLUTION")
```

The call to `m = exp.match(line)` [later in the file](https://github.com/ucbds-infra/otter-grader/blob/002f94136e7bcbfe1900d2c0e7f859990543b278/otter/assign/solutions.py#L129) when `exp` is `solution_assignment_regex` is where the bottleneck occurs.

That regular expression contains a problematic pattern that can be distilled to `(a+)+b`.  Nesting `+` quantifiers like this can cause the matcher to explore a number of cases exponential in the length of the input string for non-matching inputs like

```
aaaaaaaaaaaaaaaaaaaaaaaaaaac
```

My quick solution for that pattern is to ensure `a+` only matches the longest possible sequence via a lookahead: `(a+(?=[^a]))+b`.  In the `solution.py` code, that would translate to adding `(?=[^\w.])` after `[\w.]+`:

```
solution_assignment_regex = re.compile(r"(\s*(?:[\w.]+(?=[^\w.])(?:\[['\"].*['\"]\])*(?:,\s*)?)+\s*=).* ?# ?SOLUTION")
```

That fixes my particular use case, with the running time for the example notebook dropping down to ~1 second.  There may be better solutions that avoid the issue as well.

Thanks!
[v1.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/11366324/v1.ipynb.zip)

**Comment by taylorgibson** [comment]
I can confirm that I'm seeing similar behavior when attempting to assign v1 documents with otter-grader version 4.3.2. I'm seeing this with python 3.10.5 and 3.11.3.

I went back and tested against previous versions of `otter` to determine the version that this behavior started. 4.3.0 was the first version where the slowdown began. Reverting to 4.2.1 until the issue is resolved.

**Comment by chrispyles** [comment]
v4.3.3 (not 4.3.2) should now be available.

**Comment by sean-morris** [comment]
Thanks @chrispyles really appreciate all your work!
