### ISSUE TITLE
otter convert misses situations when no tests associated with solution

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#636]
**Describe the bug**
otter convert is not handling the situation when the v0 notebook has # SOLUTION(single or multi-line) but no tests associated with it -- the convert ignores this moment.

**To Reproduce**
1. Run otter convert on a v0 notebook with SOLUTIONS defined for a question but no TESTS
2. The resulting notebook will have skipped over handling this moment and the student notebook will contain the code or line defined as a SOLUTION still.

**Expected behavior**
This situation should turn the SOLUTION into a QUESTION in which check: false

**Versions**
python 3.10
otter v4

**Comment by sean-morris** [comment]
I wanted to clarify this. I thought the problem was related to when a # SOLUTION is defined without # TESTS; but the real issue is that if the v0 notebook had #SOLUTION but is not wrapped in a # BEGIN QUESTION, #END QUESTION it skips processing the #SOLUTION to a "..." in the student notebook. 

The solution is to wrap the #SOLUTION in #BEGIN QUESTION and #END QUESTION and then convert.

**Comment by chrispyles** [comment]
Given that there appears to be a workaround and v5, which removes the v0 assign format and the conversion tool, was just released, I'm going to close this.
