### ISSUE TITLE
grade_override.py:during_generate can not find the plugins key in the otter_config parameter

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#643]
**Describe the bug**
The grade_override plugin functionality is not accessing the plugins configuration correctly

**To Reproduce**
1. Execute otter assign with parameters for -regrades and -regrade-cred
2. An error indicating the "plugins'' key is not present in the otter_config dictionary occurs(grade_override.py, ~Line#113

**Expected behavior**
The plugin's config needs to be accessed from the assignment object also passed into the function duriung_generate

**Versions**
otter 4.3.3
python 3.10.8

**Additional context**
I proposed one solution in this [PR](https://github.com/ucbds-infra/otter-grader/pull/642); it does solve the problem and we can move forward but I am not if this is the solution you want.

**Comment by chrispyles** [comment]
@sean-morris did #642 fix this issue?

If needed, you can test this by installing otter from git and running otter assign: `pip uninstall -y otter-grader && pip install git+https://github.com/ucbds-infra/otter-grader`

**Comment by sean-morris** [comment]
yes. this is great. I will do the install from the otte-grader repo -- I had been installing from mine until the fix is released.

Thanks
