### ISSUE TITLE
Notebook validation issue related to missing ID fields

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#701]
**Describe the bug**
otter assign produces notebooks that contain a notebook validation error. This prevents them from running. The error persists even with up-to-date jupyter installation.

**To Reproduce**
1. Update jupyter (I did it using `pip install --upgrade jupyter`) 
2. Download sample notebook [demo_champollion.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/12313946/demo_champollion.ipynb.zip)
3. Run otter assign on sample notebook to produce student and autograder dirs
4. Run `jupyter notebook` in terminal
5. In jupyter notebook, navigate to autograder dir and open demo_champollion.ipynb in it
6. Try to execute the first code cell. It won't execute
7. Observe the following error output in terminal:

```
[E 2023-08-10 10:32:09.298 ServerApp] Notebook JSON is invalid: Additional properties are not allowed ('id' was unexpected)
    
    Failed validating 'additionalProperties' in code_cell:
    
    On instance['cells'][0]:
    {'cell_type': 'code',
     'execution_count': None,
     'id': 'd8e6cbc3',
     'metadata': {'deletable': False, 'editable': False},
     'outputs': ['...0 outputs...'],
     'source': '# Initialize Otter\n'
               'import otter\n'
               'grader = otter.Notebook("demo_ch...'}
[W 2023-08-10 10:32:09.302 ServerApp] Notebook dist/autograder/demo_champollion.ipynb is not trusted
```

**Expected behavior**
The code cell should execute without a problem and the "Notebook JSON is invalid" error shouldn't appear

**Versions**

Python version: 3.10.12
Otter-Grader version: 5.1.0

**Additional context**
```
(otter-env) champollion@new-host-7 jupyterhub % jupyter --version
Selected Jupyter core packages...
IPython          : 8.12.2
ipykernel        : 6.25.0
ipywidgets       : 8.1.0
jupyter_client   : 8.1.0
jupyter_core     : 5.3.0
jupyter_server   : 2.7.0
jupyterlab       : 4.0.4
nbclient         : 0.8.0
nbconvert        : 7.7.3
nbformat         : 5.9.2
notebook         : 7.0.2
qtconsole        : 5.4.3
traitlets        : 5.7.1

(otter-env) champollion@new-host-7 demo_champollion % which -a jupyter
/Users/champollion/miniconda3/envs/otter-env/bin/jupyter
/Users/champollion/.pyenv/shims/jupyter
(otter-env) champollion@new-host-7 demo_champollion % which -a otter     
/Users/champollion/miniconda3/envs/otter-env/bin/otter
/Users/champollion/.pyenv/shims/otter
```

Autograder output is attached here: 
[demo_champollion.ipynb_autograder_output.zip](https://github.com/ucbds-infra/otter-grader/files/12314026/demo_champollion.ipynb_autograder_output.zip)

**Comment by chrispyles** [comment]
The notebook you shared is on nbformat v4.4 (you can see this in the notebook JSON), which is outdated (the ID field was added in nbformat v4.5) ([ref](https://stackoverflow.com/a/71217353/22195928)). We had a patch for removing cell IDs from _every_ notebook but it was removed in v5.1.0 due to #677. (It's very irritating that this breaking change to the format was added in a minor version and not a major version.) I'll see if I can bring the patch back but only apply it for notebooks with version <= 4.4.
