### ISSUE TITLE
bibtex causes export cell to fail

### ISSUE THREAD

**Issue by bdsomer** [ucbds-infra/otter-grader#714]
**Describe the bug**
When running the export cell of a notebook that has a call to `otter.export.export_notebook` in a previous cell, the final export cell fails with the following output:

```
Running your submission against local test cases...


[IPKernelApp] WARNING | bibtex had problems, most likely because there were no citations
```

and the following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 2
      1 # Save your notebook first, then run this cell to export your submission.
----> 2 grader.export(run_tests=True)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/utils.py:166, in grading_mode_disabled(wrapped, self, args, kwargs)
    164 if type(self)._grading_mode:
    165     return
--> 166 return wrapped(*args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/utils.py:153, in incompatible_with.<locals>.incompatible(wrapped, self, args, kwargs)
    151     else:
    152         return
--> 153 return wrapped(*args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/utils.py:203, in logs_event.<locals>.event_logger(wrapped, self, args, kwargs)
    201 except Exception as e:
    202     self._log_event(event_type, success=False, error=e)
--> 203     raise e
    205 else:
    206     self._log_event(event_type, results=results, question=question, shelve_env=shelve_env)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/utils.py:197, in logs_event.<locals>.event_logger(wrapped, self, args, kwargs)
    194     question, results, shelve_env = wrapped(*args, **kwargs)
    196 else:
--> 197     results = wrapped(*args, **kwargs)
    198     shelve_env = {}
    199     question = None

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/notebook.py:447, in Notebook.export(self, nb_path, export_path, pdf, filtering, pagebreaks, files, display_link, force_save, run_tests)
    444         display(HTML(out_html))
    446 if pdf_created or not otter_nb_config.get(REQUIRE_CONFIRMATION_NO_PDF_EXPORT_KEY, False):
--> 447     continue_export()
    448 else:
    449     display_pdf_confirmation_widget(
    450         otter_nb_config.get(NO_PDF_EXPORT_MESSAGE_KEY), continue_export)

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/notebook.py:429, in Notebook.export.<locals>.continue_export()
    427 if run_tests:
    428     print("Running your submission against local test cases...\n")
--> 429     results = grade_zip_file(zip_path, nb_path, self._path)
    430     print(
    431         "Your submission received the following results when run against " + \
    432         "available test cases:\n\n" + indent(results.summary(), "    "))
    434 if display_link:
    435     # create and display output HTML

File /srv/conda/envs/notebook/lib/python3.11/site-packages/otter/check/utils.py:91, in grade_zip_file(zip_path, nb_arcname, tests_dir)
     88 print(results.stderr.decode("utf-8"))
     90 if results.stderr:
---> 91     raise RuntimeError(results.stderr)
     93 with open(results_path, "rb") as f:
     94     results = dill.load(f)

RuntimeError: b'[IPKernelApp] WARNING | bibtex had problems, most likely because there were no citations\n'
```

**To Reproduce**
Make a notebook `example.ipynb` with the following content:
```
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# ASSIGNMENT CONFIG\n",
    "run_tests: false"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Homework"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# BEGIN QUESTION\n",
    "name: q1c\n",
    "manual: true"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "tags": []
   },
   "source": [
    "Example question"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# BEGIN SOLUTION"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Example solution"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# END SOLUTION"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# END QUESTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import otter\n",
    "\n",
    "otter.export.export_notebook(\"example.ipynb\", filtering=True, pagebreaks=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "end of homework"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```
and then use `otter assign` to assign the notebook. Upon running the export cell in the student notebook, the aforementioned error occurs.

**Expected behavior**
The export cell exports successfully.

**Versions**
Python 3.11.0, Otter 5.1.2

**Additional context**
Here's an overview of the stack trace of the problem:
- The export cell runs an `nbconvert.ExecutePreprocessor` on the notebook (https://github.com/ucbds-infra/otter-grader/blob/master/otter/execute/__init__.py#L94)
- The `nbconvert.ExecutePreprocessor` runs the cell with the call to `otter.export.export_notebook`, which runs https://github.com/ucbds-infra/otter-grader/blob/master/otter/export/__init__.py#L42. In this case, `Exporter` is a `PDFViaLatexExporter`.
- Calling `Exporter.convert_notebook` calls `PDFViaLatexExporter#convert_notebook`, which in turn calls `nbconverter.PDFExporter#export` (https://github.com/ucbds-infra/otter-grader/blob/master/otter/export/exporters/via_latex.py#L66)
- This eventually calls `PDFExporter#from_notebook_node`, which calls `PDFExporter#run_bib` (https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/pdf.py#L200)
- The `bibtex` command generates the warning, which the `PDFExporter` outputs (https://github.com/jupyter/nbconvert/blob/main/nbconvert/exporters/pdf.py#L177)

As the warning states, "bibtex had problems, most likely because there were no citations." I am almost certain that the lack of citations is causing the warning here, and as [this issue](https://github.com/jupyter/help/issues/405) suggests, this warning is fine to ignore if there are no citations in the notebook. In order to fix this issue, we have to somehow suppress this warning or stop `bibtex` from running in the first place. The latter option might have unintended consequences on notebooks that use `bibtex` for citations though.

**Comment by chrispyles** [comment]
Generating PDFs while in grading mode (e.g. when performing the submission zip validation) is unsupported. otter patches the Notebook class when in grading mode to prevent errors like this from occurring, but since you’re bypassing Notebook to generate the PDF, it can’t ensure it doesn’t get run. To fix, you should remove direct calls to `export_notebook` and let Notebook generate the PDF for you (by setting `export_cell: pdf: true` in the assignment config).

**Comment by bdsomer** [comment]
Okay, I see. Some notebooks that Data 100 uses have cells like this before the final export cell:

```
from otter.export import export_notebook
from os import path
from IPython.display import display, HTML
export_notebook("example.ipynb", filtering=True, pagebreaks=True)
if(path.exists('example.pdf')):
    display(HTML("Download your PDF <a href='example.pdf' download>here</a>."))
else:
    print("\n Pdf generation fails, please try the other methods described above")
```

and it seems that the `require_no_pdf_ack` configuration option takes care of this logic for the most part, as described in the docs [here](https://otter-grader.readthedocs.io/en/latest/otter_assign/notebook_format.html#submission-export-cells). However, upon a successful export, the export cell still gives an output of "Your submission has been exported. Click here to download the zip file." Is there a way to provide a link to download the PDF in the export cell's output message?

**Comment by chrispyles** [comment]
The zip link linked in the output will contain the PDF.

**Comment by bdsomer** [comment]
Got it. In that case, I'll need to figure out how to get Gradescope to run an autograder on the notebook and allow students to assign pages to the PDF when uploading the zip file. Please let me know if you have any ideas. Because this isn't an issue with otter, I'll close this issue for now.
