### ISSUE TITLE
Inserting blank line at the end of a solution cell gives odd behavior

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#718]
When a blank line is inadvertently inserted as the last line of a solution cell in the master notebook, otter grader thinks that the blank line is the correct result. This can be hard to debug because the blank line is easily overlooked.  

Ideally, the blank line should lead to at least a warning at compile time, since I can't think of any situations in which I might intentionally want to insert a blank line at the end of a solution cell.

Python version: 3.10.12
Otter-Grader version: 5.1.2

**Comment by chrispyles** [comment]
This should be fixed for Python 3.9+ by #713 (released in v5.2.0).
