### ISSUE TITLE
Submission link errors

### ISSUE THREAD

**Issue by mihranmiroyan** [ucbds-infra/otter-grader#719]
The link to the submission zip file generated by export cell throws "File is not UTF-8 encoded" error.

**To Reproduce**
1. otter assign [lab01.ipynb.zip](https://github.com/ucbds-infra/otter-grader/files/12424390/lab01.ipynb.zip)
2. run the cells of lab01.ipynb from the autograder folder
3. click on the link generated by the export cell.
4. throws an error: 
<img width="496" alt="Screenshot 2023-08-23 at 6 03 17 PM" src="https://github.com/ucbds-infra/otter-grader/assets/98374654/5f09a1e5-519b-4c8c-96f3-e429a75b7fa9">

**Expected behavior**
When clicking on the submission link, it should download the submission zip file.

**Versions**
Python 3.11.0; Otter-grader 5.1.1

**Additional context**
Datahub [environment](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100/image/environment.yml); we just downgraded otter to 4.4.1 (it was 5.1.1).

Requirement.txt for otter: [requirements.txt](https://github.com/ucbds-infra/otter-grader/files/12424371/requirements.txt)

**Comment by balajialg** [comment]
Additional info about this behavior across other versions:

Otter versions 5.0.0 and 5.0.2 - Reported error messages and didn't generate the link to download the zip file
Otter versions 5.1.1 and 5.1.2 - Clicking the zip file generated the UTF 8 error reported above!
