### ISSUE TITLE
Clearer error message when notebook does not contain expected metadata

### ISSUE THREAD

**Issue by aidansan** [ucbds-infra/otter-grader#722]
**Is your feature request related to a problem? Please describe.**
grader.check throws "Key Error: 'otter'" when you try to run tests and there is no notebook metadata.

**To Reproduce**
1. Rename a student notebook
2. Copy student notebook into same directory with master notebook (or any other notebook with the same original name as the student notebook and no test metadata)
3. Run initialize otter cell in student notebook
4. Run grader.check cell in student notebook
5. See error

**Describe the solution you'd like**
otter should throw an error like "the notebook hw01.ipynb does not have Otter-Grader metadata. Ensure you have specified the correct notebook path."

**Additional context**

~**Describe the bug**~
~After copy a notebook using the "Make a copy" function in jupyter, grader.check throws "Key Errror: 'otter'"~

~**To Reproduce**~
~Steps to reproduce the behavior:~
~1. Go to "File" menu~
~2. "Make a copy..."~
~3. Run initialize otter cell~
~4. Run grader.check cell~
~4. See error~

~**Expected behavior**~
~The grader should run the corresponding tests for the question~

**Versions**
Python: 3.11.4 (Using anaconda through anaconda navigator)
Otter: 5.1.1

![Screenshot 2023-08-23 at 8 18 17 PM](https://github.com/ucbds-infra/otter-grader/assets/48337132/cf620a3c-bc8d-4e50-91f4-d241a8ae991f)
![Screenshot 2023-08-23 at 9 26 11 PM](https://github.com/ucbds-infra/otter-grader/assets/48337132/0bd1144a-63e4-4f53-8199-41008cd93ded)

**Comment by chrispyles** [comment]
Can you share the notebook that produced this error? Feel free to send in slack if you don't want it posted publicly.

**Comment by chrispyles** [comment]
Resolving over slack -- this is not an issue with otter

**Comment by chrispyles** [comment]
Reopening to track addition of a clearer error message in this case. Something like "the notebook hw01.ipynb does not have Otter-Grader metadata. Ensure you have specified the correct notebook path."

**Comment by chrispyles** [comment]
This should be fixed in v5.2.0. Instead of the `KeyError`, you'll get an error that reads `ValueError: Test q1 not found`.
