### ISSUE TITLE
CLI documenation: otter grader 4.4.1 versus 5

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#727]
**Is your feature request related to a problem? Please describe.**
The documentation no longer has otter grader 4.4.1 cli commands. The problem stems from otter grader 5 not being able to grade notebooks created with 4.4.1. 

**Describe the solution you'd like**
Either make otter grader 5 grade backwards compatible to otter grader 4 notebooks or restore pieces of the otter grader 4 cli documentation.

The problem with otter 5 trying to grade otter 4 notebooks seems to be in the setup.sh file -- There may not be an easy way to fix this. I am pretty sure the wget command is not on the standard ubuntu image. 
![image](https://github.com/ucbds-infra/otter-grader/assets/1514995/c15d0363-7081-44cc-aead-b5f045d1a302)

The path may be to modify the setup.sh in the autograder.zip file.

**Additional context**
We have a bunch of instructors learning to use otter who are running otter 5 cli grade commands against otter 4 notebooks. 

Thanks

**Comment by chrispyles** [comment]
I've re-enabled the docs for v4.4.1. They can be found [here](https://otter-grader.readthedocs.io/en/v4.4.1/).
