### ISSUE TITLE
Patch : 4.4.1: Sort final_grades.csv

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#738]
**Is your feature request related to a problem? Please describe.**
I am hoping we get the final_grades.csv sorted by notebook name.

**Describe the solution you'd like**
I am looking at this line in v4.4.1:
https://github.com/ucbds-infra/otter-grader/blob/1e489711837ff0a5fef9f7d942d12f32fcfb9cfa/otter/grade/utils.py#L38

I made this change and tested it off the v4.4.1 tag:
https://github.com/sean-morris/otter-grader/blob/d039ec81379f1e26ee8c7185fe5ed5f139305091/otter/grade/utils.py#L38

Can we put this in as a patch(or whatever it would be) on v4.4.1?

**Describe alternatives you've considered**
We had this request from a colleague at Sienna College who said of course he can just hit sort on his spreadsheet software but figured the change was pretty easy.

**Additional context**
Example final_grades.csv - you can see they are not sorted by the first column, file
```
file,q1_1,q1_2,q1_3,q1_4,q1_5,q1_6,q1_7,q2_1,q2_2,q2_3,q2_4,q2_6,q3_3,q3_4,q3_5,q4_1,q4_3,percent_correct
NTHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,4,4,4,0,5,5,0.42857142857142855
CDHw03.ipynb,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,1,1,0.08571428571428572
ICHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,4,0,0,0,5,5,0.3142857142857143
AKHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,4,0,0,4,5,5,0.37142857142857144
RVHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,4,4,0,4,5,5,0.42857142857142855
KGHw03.ipynb,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
LSHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,4,4,0,0,1,1,0.2571428571428571
VNHw03.ipynb,0,0,0,0,0,0,4,0,0,0,4,0,0,0,0,1,1,0.14285714285714285
```

**Comment by moustakas** [comment]
Thanks @sean-morris and thank you to the whole dev team for a terrific tool.

To clarify my personal use case: I'm recording the reported Otter grades in Canvas by-hand, so having the final `csv` file alphabetized by `file` (which, for me, starts with the last name of each student) is a small, but notable convenience. 

For the record, at the moment I'm just doing (from the command line)
```
python -c "import pandas as pd ; print(pd.read_csv('final_grades.csv').sort_values('file'))"
```
and reading off the grades.

Note: `Sienna College` --> `Siena College`
