### ISSUE TITLE
Exercise file quantifierRaising_vs_typeshifting.txt doesn't open in 2.6.0 SE + TE on Mac

### ISSUE THREAD

**Issue by champoll** [ucbds-infra/otter-grader#753]
Exercise file quantifierRaising_vs_typeshifting.txt doesn't open in 2.6.0 SE + TE on Mac. 
[quantifierRaising_vs_typeshifting.txt](https://github.com/ucbds-infra/otter-grader/files/13179324/quantifierRaising_vs_typeshifting.txt)

**Comment by chrispyles** [comment]
Is this an otter-related bug?

**Comment by champoll** [comment]
So sorry, this was meant for another project!
