### ISSUE TITLE
Intercell seeding breaks cell magics

### ISSUE THREAD

**Issue by chrispyles** [ucbds-infra/otter-grader#754]
For cells that use cell magics, intercell seeding may cause errors that prevent those cells from executing. For example, a cell like

```
%%sql
-- just run this cell --
SELECT * FROM sqlite_master WHERE type='table';
```

becomes

```
np_V8HY0L.random.seed(42)
random.seed(42)
%%sql
-- just run this cell --
SELECT * FROM sqlite_master WHERE type='table';
```

I think the solution here should be just to not insert intercell seeding code for cells that start with `%%`.

**Comment by rohanjha123** [comment]
If there is no intercell seeding for magic cells, would we be able to autograde things like the SQL RAND() functions without having to specify a seed in every RAND() call across multiple cells?

**Comment by chrispyles** [comment]
> If there is no intercell seeding for magic cells, would we be able to autograde things like the SQL RAND() functions without having to specify a seed in every RAND() call across multiple cells?

The current implementation of intercell seeding does not support seeding SQL; it only seeds `numpy` and the built-in `random` library. So yes, to seed RAND in SQL, you would need to add the seeds yourself.
