### ISSUE TITLE
Exporting pdf's to other gradescope assignments fails when students add in external files

### ISSUE THREAD

**Issue by rohanjha123** [ucbds-infra/otter-grader#764]
**Is your feature request related to a problem? Please describe.**
Sometimes, students may add in their own .png/.jpg files into the .ipynb notebooks. When this happens, the zip (including the pdf) will generate fine in the notebook. However, when the student submits the zip to Gradescope, the pdf will not be able to be generated (as those necessary files aren't included), thus leading to an error.

**Describe the solution you'd like**
I would love it if any files students use in their .ipynb notebooks can be included in the generated .zip. If this isn't possible, maybe the pdf included in the zip can be sent to the other Gradescope assignment rather than recreating the pdf from scratch.

**Describe alternatives you've considered**
If the above options are not possible, it'd be great if students could get a warning that they have dragged in images/files which will mess up the Gradescope submission.

**Additional context**
I've dm'ed reproducible notebooks to Chris!

**Comment by chrispyles** [comment]
@765 adds the ability to use the submission PDF instead of generating a new one. To use it, set `generate: use_submission_pdf: true` in the assignment config.

**Comment by rohanjha123** [comment]
Thanks sm Chris! Just to confirm, I will only be able to use this when otter 5.3 releases right? If that's the case, I will upgrade data 100 and econ 148 datahub to otter 5.3 as soon as it drops.

**Comment by chrispyles** [comment]
Yes, that's correct
