### ISSUE TITLE
ottr::export force_save isn't working

### ISSUE THREAD

**Issue by chrispyles** [ucbds-infra/otter-grader#767]
https://github.com/ucbds-infra/otter-grader/issues/766#issuecomment-1903313657

**Comment by chrispyles** [comment]
@dbroockman I'm not able to reproduce these failures in force_save locally. Are you using JupyterLab, Retrolab, or the old Jupyter notebook interface on the hub?

**Comment by dbroockman** [comment]
Same, it works for me locally. Errors are appearing on Berkeley Datahub. Here's an example link: https://r.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdbroockman%2FPS3-SP24-Public&branch=main&urlpath=tree%2FPS3-SP24-Public%2Fw2%2Fw2a1v2%2Fstudent%2FWeek2_Activity1.ipynb

**Comment by chrispyles** [comment]
Unfortunately I can't access the hub since I no longer have a canvas account. Can you share a screenshot of the full page so I can figure out which you're using?

**Comment by dbroockman** [comment]
<img width="1661" alt="Screenshot 2024-01-23 at 9 11 27 AM" src="https://github.com/ucbds-infra/otter-grader/assets/6677808/9bc9948d-ebb8-4660-968b-981730c79921">

**Comment by chrispyles** [comment]
Can you try running `pip show retrolab` from the terminal on the hub and send the output? maybe the issue is related to the specific version of retrolab.

**Comment by chrispyles** [comment]
I assume it's a more recent version than 0.2.2 (mine), since after upgrading to the latest version I am now able to reproduce. Will look into it.

**Comment by dbroockman** [comment]
Thanks. In Terminal `pip show retrolab` gives me package not found.

**Comment by chrispyles** [comment]
Can you select "About Jupyter Notebook" and send a screenshot?

**Comment by dbroockman** [comment]
<img width="459" alt="Screenshot 2024-01-25 at 5 48 06 PM" src="https://github.com/ucbds-infra/otter-grader/assets/6677808/b7ca0ce4-8f29-4fc7-809b-3a7ea3c375e1">

**Comment by chrispyles** [comment]
I think this is an upstream bug in Jupyter Notebook. opened https://github.com/jupyter/notebook/issues/7225

**Comment by chrispyles** [comment]
Until that gets fixed, I've come up with a rather hacky solution that involves installing a JupyterLab extension that leaves a hook ottr can call to force-save the notebook. Since there's [already an Otter-Grader lab extension](https://github.com/chrispyles/otter-grader-labextension) I'm going to reuse it. Will let you know when the version that needs to be installed on the hub is available.

**Comment by chrispyles** [comment]
@dbroockman I've sent off v1.5.0 of ottr to CRAN; I'll follow up once it's installable. v1.5.0 will require the Python package [ottr_force_save_labextension](https://github.com/chrispyles/ottr-force-save-labextension) to be installed in order for force-save to work, so when you make the request to upgrade ottr on the hub, make sure to also ask for package to be installed.

**Comment by chrispyles** [comment]
ottr v1.5.0 is now installable from CRAN and github, so feel free to open an issue on berkeley-dsep-infra/datahub to install it and ottr_force_save_labextension

**Comment by dbroockman** [comment]
Thank you!
