### ISSUE TITLE
Blank tests summary when exporting student's notebook from tutorial

### ISSUE THREAD

**Issue by glciampaglia** [ucbds-infra/otter-grader#773]
**Describe the bug**
Hi all, first of all, thanks for creating this tool. I'm coming from nbgrader and it's great to see so many cool features!

I am working through the tutorial and I noticed one odd behavior. I generated the student notebook (`/tutorial/dist/student/demo.ipynb`), and tried to export it to see what students would see. The export cell at the end of the notebook does generate a zip file. However, it is supposed to also give a summary of all the tests, and this summary comes out blank:

![image](https://github.com/ucbds-infra/otter-grader/assets/1506860/3899b791-dd7b-4808-a252-45011d2dd4e0)

I've tried to do the same on the generated solution (`/tutorial/dist/autograder/demo.ipynb`) and there it does produce a summary:

![image](https://github.com/ucbds-infra/otter-grader/assets/1506860/1dbcfca8-ae6c-4669-a119-d32a0301310d)

I thought perhaps the issue is because I did not complete the questions. So I've tried again, but pasting into the student notebook the solutions from the other notebook, but got the same behavior. So the issue is not because the tests are failing.

**To Reproduce**
1. Download [tutorial zip file](https://otter-grader.readthedocs.io/en/latest/_static/tutorial.zip)
2. Run otter assign
3. Open `/tutorial/dist/student/demo.ipynb` and run all cells

**Expected behavior**
The export cell should list the result of all tests, but a blank line is displayed instead.

**Versions**
Please provide your Python and Otter versions. The Otter can be obtained using `from otter import __version__`

Python: 3.11.7
Otter: 5.4.0
Jupyterlab: 3.6.3

**Additional context**
I've installed Otter via conda instead of pip, using conda-forge channel.

**Comment by chrispyles** [comment]
Thanks for the bug report @glciampaglia. I've fixed this in the commit referenced above. The docs will be updated the next time there is a major release (which should be soon -- I'm fixing something and intend to release v5.4.1 today or tomorrow).
