### ISSUE TITLE
Add Points Per Question and Total Points to final_grades.csv

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#803]
**Is your feature request related to a problem? Please describe.**
I want to include the points per question in the final_grades.csv file so instructors know the point value assigned to each question.

**Describe the solution you'd like**
I am thinking of a few options:
1) The totals listed at the bottom of final_grades.csv with a line between scores and the totals
![image](https://github.com/ucbds-infra/otter-grader/assets/1514995/aff4b85c-50ba-4ba9-adc2-26fb3c5dfe06)

2) 1) The totals list at the top of final_grades.csv underneath the column labels.
![image](https://github.com/ucbds-infra/otter-grader/assets/1514995/a1218f85-d5e7-4199-ad46-62fec08bb6b6)

3) I could write the totals into a separate file, points_per_question.csv.

I can submit a PR with whatever option(or another option) people think will work.

I am also wondering if people are interested in adding a total points earned column next to the percent_correct:
![Screenshot 2024-05-16 at 5 04 06 PM](https://github.com/ucbds-infra/otter-grader/assets/1514995/52ecfb60-a215-4258-b47c-333d67c0af7c)

**Comment by chrispyles** [comment]
Option #1 may break programmatic CSV file parses, so I'd vote for #2. happy to review a PR.

**Comment by sean-morris** [comment]
This is taken care of PR #810
