### ISSUE TITLE
Otter-grader problems with juno app on ios

### ISSUE THREAD

**Issue by Tejas-Ketkar** [ucbds-infra/otter-grader#805]
**Describe the bug**
On Juno for the ipad otter-grader cannot accurately check solutions to questions.

**To Reproduce**
1. Juno app on ipad-os, load up a juypter notebook which needs to use autograder
2. Click on any autograding cell
3. Scroll down to the result

**Expected behavior**
The expected behavior is that the test case should pass, instead I see some output. For example

```
arr = np.array([1,2,3,4,5])
arr
```

```
grader.check("q1")
```
```
q1 results:
q1 - 1 result:
    ❌ Test case failed
    Trying:
        type(arr) is np.ndarray
    Expecting:
        True
    **********************************************************************
    Line 1, in q1 0
    Failed example:
        type(arr) is np.ndarray
    Exception raised:
        Traceback (most recent call last):
          File "/var/mobile/Containers/Data/Application/6D34FD75-2F6D-4753-98C5-E18B7D91A961/Library/Application Support/com.rationalmatter.junoapp/python-home/lib/python3.10/doctest.py", line 1346, in __run
            exec(compile(example.source, filename, "single",
          File "", line 1, in 
            type(arr) is np.ndarray
        NameError: name 'arr' is not defined
q1 - 2 result:
    ❌ Test case failed
    Trying:
        all(arr == np.array(np.array([1, 2, 3, 4, 5])))
    Expecting:
        True
    **********************************************************************
    Line 1, in q1 1
    Failed example:
        all(arr == np.array(np.array([1, 2, 3, 4, 5])))
    Exception raised:
        Traceback (most recent call last):
          File "/var/mobile/Containers/Data/Application/6D34FD75-2F6D-4753-98C5-E18B7D91A961/Library/Application Support/com.rationalmatter.junoapp/python-home/lib/python3.10/doctest.py", line 1346, in __run
            exec(compile(example.source, filename, "single",
          File "", line 1, in 
            all(arr == np.array(np.array([1, 2, 3, 4, 5])))
        NameError: name 'arr' is not defined
```
**Versions**
Otter Version: 5.5.0, Python Version: python3

**Additional context**
When I go onto the package manager on Juno, it says otter-grader is compatible, so I believe this is a bug that needs fixing, let me know if this isn’t the case.

**Comment by chrispyles** [comment]
The tests are failing with `NameError: name 'arr' is not defined` which means that `arr` did not exist in the global environment when the check cell ran; had you run the cell that defines `arr` before running the `grader.check` cell?

**Comment by Tejas-Ketkar** [comment]
I think so, I tried to follow the same steps on a computer and on an ipad. I've uploaded both to the google drive link, so you can see what it looks like on my end

https://drive.google.com/drive/folders/1SLkdWzIEyNilgmEd7UiEvMYg53bHpUw4?usp=drive_link

**Comment by chrispyles** [comment]
Is this generated from an Otter Assign notebook? If so, can you share that as well? Feel free to PM it to me in Slack (link in README) if you don't want it posted publicly.

**Comment by Tejas-Ketkar** [comment]
Sure, I've sent you the message on Slack.
