### ISSUE TITLE
Plugins and submission_metadata

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#811]
**Describe the bug**
This is either my problem or a bug but it looks like the submission_metadata.json is required anytime you specify a [plugin](https://github.com/sean-morris/otter-grader/blob/48f4a9ec1737893a8a08348049ab97796fbb7842/otter/run/run_autograder/runners/python_runner.py#L83)

**To Reproduce**
1. I created a separate project for a plugin to write out the results of each notebook graded in a copyable format.
2. Install the plugin via pip in my environment
3. Specify the plugins attribute in the autograder.zip/otter_config.json file
4. It appears to load the plugin but requires a submission_metadata.json file to be present and a file not found error occurs.

**Expected behavior**
I do not think my plugin needs the submission_metadata.json file to execute correctly but maybe I am missing something here.

**Versions**
otter 5.5.0(with my additional pieces that are planned for 5.6.0

**Additional context**

**Comment by chrispyles** [comment]
Is this plugin meant to run in the grading container? If so, the plugin system assumes the existence of the submission_metadata.json file, and its presence is required. We patch this in Otter Run with [this](https://github.com/sean-morris/otter-grader/blob/65c5ef8edc2c465fb737cdd8f222b227d58eb644/otter/run/__init__.py#L44), but I don't think there's a similar patch in Otter Grade (which I assume is where you're seeing the error). Adding such a patch is as simple as adding `RUN touch /autograder/submission_metadata.json` to otter/grade/Dockerfile.

**Comment by sean-morris** [comment]
Great perfect. Thanks. Yes it is meant to be run in a grading container.

**Comment by sean-morris** [comment]
@chrispyles I did not end up using the plugin route on issue #814. Do you want this `touch` command inserted into the grade/Dockerfile anyway? Otherwise, we can close this issue.

**Comment by chrispyles** [comment]
I think it would be a good idea to add it anyway so that we don't get errors like this in the future.
