### ISSUE TITLE
Otter Grade: Write out Individual Results as well as final_grades.csv

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#814]
**Is your feature request related to a problem? Please describe.**
Currently, to understand what might have gone wrong in a notebook that has points taken off according to the final_grades.csv, you need to turn around and run `otter run` on that notebook. This is a problem for instructors using the service we provide.

**Describe the solution you'd like**
I would like the default behavior to be that we write the ``GradingResults`` objects summary field to a file whose name matches the notebook name. ``otter grade`` would then return a final_grades.csv and a folder of files each with their respective notebooks grading results. 

**Describe alternatives you've considered**
This could be done via a plugin but first, we would need a new plugin event supported that occurs post-otter grade. The current events are tied to otter run.  I am not quite sure the plugin is worth it; it is hard to believe that someone running otter grade would not want to see the individual notebook results.

**Additional context**
Also, I run otter grade in the context of a web application returning the results to the instructor. They are not running otter grade themselves(nor otter run for that matter) in most cases.

**Comment by sean-morris** [comment]
@chrispyles when you get a chance. I have a non-plugin solution ready -- it is pretty easy but not sure you want this behavior in the main distribution.

**Comment by chrispyles** [comment]
@sean-morris I'm fine with having this be part of the main package -- it sounds very useful -- but I'd like to put it behind a flag rather than having it be the default behavior (I don't want us generating several potentially unnecessary files in the user's system unless they ask for it).
