### ISSUE TITLE
Otter Grade: Progress Queue

### ISSUE THREAD

**Issue by sean-morris** [ucbds-infra/otter-grader#827]
**Is your feature request related to a problem? Please describe.**
 Currently, when a user submits a set of notebooks to be graded, I cannot give any feedback related to grading progress.

**Describe the solution you'd like**
I would like to give feedback to the user related to progress during the otter grade process by maintaining a queue that is written too during various moments in the `otter grade` process. This might include when the process starts, how many notebooks are being graded, when a notebook is complete, etc.

**Describe alternatives you've considered**
There is no real alternative here.

**Additional context**
I am running otter grade via a web application where I would like to report progress on grading to the web application for the user to see.

**Comment by sean-morris** [comment]
I have a rough draft of what this might look like and how the queue might be exposed to users in use now. If you are interested in integrating the functionality, I can put together a PR. I am definitely interested in how you might approach this @chrispyles

**Comment by chrispyles** [comment]
This sounds fine to me. I don't have any immediate thoughts on how to implement this, but I'd like to make sure that something like this is opt-in so it doesn't introduce unnecessary overhead for users who don't need it.
