### ISSUE TITLE
Make test functions get access to global variables

### ISSUE THREAD

**Issue by muhangao** [ucbds-infra/otter-grader#837]
I'm writing test functions for autograder using OK Test format. However, for some functions, there're **variable not defined**  error.

I tried to define them again in the test['setup'], and it's not working. I'm wondering is there any way to make test functions get access to global variables?

**Comment by muhangao** [comment]
Never mind, after adding nltk.download('punkt_tab') everything works.

**Comment by chrispyles** [comment]
Just adding info for the benefit of anyone who comes across this issue:

Otter does not support sharing variables declared in tests across test cases; there is an open FR for this (#426) but it is not currently planned. Otter also does not support all fields of the OK test format (including setup and teardown).

**Comment by muhangao** [comment]
Let me make sure I understand: So can the test function gain access to variables created by students?

**Comment by chrispyles** [comment]
Yes, anything declared in the student code should be accessible, you just can’t share variables between test cases that aren’t in the student code.
