### ISSUE TITLE
Dockerfile is different in 5.7.0 and no longer works

### ISSUE THREAD

**Issue by nibheis** [ucbds-infra/otter-grader#849]
**Describe the bug**
From 5.6.0 to 5.7.0, the Dockerfile got changed and now building the image fails.
New lines in Dockerfile:
```
ENV PATH=/root/miniforge3/bin:$PATH
ADD __otter-grader /tmp/otter-grader
RUN mamba run -n otter-env pip install /tmp/otter-grader
RUN rm -rf /tmp/*
```
The build fails on the `ADD __otter-grade /tmp/otter-grader` line.

**To Reproduce**
1. run `otter grade` on docker, on a **remote** docker host (via ssh).

Maybe the `ADD __...` line works on a local docker host?
TBH, I don't know what is the purpose of the double underscore - I did not find any information in the docker documentation.

**Expected behavior**
Image building and grading from `otter grade` work as expected.

**Versions**
Only happens with 5.7.0.

**Additional context**
If I comment out those 4 lines in the Dockerfile (i.e. reverting to the Dockerfile from 5.6.0), then the docker image builds correctly and grading occures correctly too.

**Comment by chrispyles** [comment]
The “new” contents are actually used for testing the docker image, looks like I accidentally committed the changes. I’ll remove them and release v5.7.1 tonight.

**Comment by nibheis** [comment]
Thank you very much for your quick action ; it was my understanding that those lines were for your debugging :-)

**Comment by chrispyles** [comment]
v5.7.1 is now up
