### ISSUE TITLE
Comparison with related software, especially nbgrader

### ISSUE THREAD

**Issue by jedbrown** [ucbds-infra/otter-grader#85]
It's interesting to see an active project with momentum in this space, but it would be really useful to have a comparison with existing tools. In comparison to nbgrader, it seems like question prep takes a bit more work with Otter, but perhaps can better support cases in which students can approach the problem in different ways. And it looks like Gradescope is a recommended way to write feedback, versus the built-in grading/feedback support in nbgrader. Perhaps you could write a brief comparison on the docs site to make it clear what we'd be getting/giving up in switching to Otter to help prospective users make more informed decisions.

**Comment by 1kastner** [comment]
This question has also come up at https://discourse.jupyter.org/t/ngshare-a-solution-for-using-nbgrader-with-jupyterhub-and-kubernetes/4724

**Comment by chrispyles** [comment]
Implemented in #355
