### ISSUE TITLE
Grader Failed to Build on Gradescope

### ISSUE THREAD

**Issue by codingPie** [ucbds-infra/otter-grader#883]
I currently use otter grader 6.0.2. My most recent grader failed to build. The error is 
ERROR conda.core.link:_execute(951): An error occurred while installing package 'defaults::nb_conda_kernels-2.5.2-py312h06a4308_0'.

Before that, I have this line: ModuleNotFoundError: No module named 'jupyter_server'. Is this related to the most recent otter grader update? Should I upgrade to 6.0.4 to have the grader built successfully? If not, anybody else experienced similar issue?

Thanks!

**Comment by chrispyles** [comment]
Yes, this should be fixed in v6.0.4. Please upgrade and let me know if it works.

**Comment by codingPie** [comment]
Thanks so much for the quick reply Chris. @chrispyles 

One more question, do students need to upgrade their grader version as well? I had some challenge last week asking students upgrade to 6.0.2. If possible, I hope they don't have to upgrade.

**Comment by chrispyles** [comment]
No, students don’t need to upgrade

**Comment by codingPie** [comment]
Thanks @chrispyles. I was able to have the grader built on Gradescope and grade some files but the grader starts to fail grading now. Not sure whether this is an otter grader issue or Gradescope issue. I am going to keep trying.

**Comment by codingPie** [comment]
Everything works well.

**Comment by SaiUCM** [comment]
Hello @codingPie ,

I'm encountering the same error. Otter 6.0.4 installed successfully on JupyterHub, but the autograder setup in Gradescope keeps failing. Do you have any insights on this?

**Comment by codingPie** [comment]
Hi @SaiUCM I use Jupyter notebook, not JupyterHub. I guess it should be the same. Since I upgrade my Otter grader to 6.0.4, I was able to build the container on Gradescope and all student files are graded without any problem. You may want to check the version of your otter grader to confirm the upgrader is successful. Good luck!

**Comment by SaiUCM** [comment]
Hi @codingPie, Thanks for your suggestion! I upgraded my Otter version to 6.0.4, and the container build on Gradescope was successful. However, even though the test cases pass in the student notebooks, they are still failing in Gradescope. Do you have any idea why this might be happening?

**Comment by codingPie** [comment]
Sorry I don't have any idea. Actually, I am struggling with a similiar issue even though the previous assignment worked successfully after the grader update. I am waiting for help on the issue of test cases passed on the notebook but failed on Gradescope as well.

**Comment by chrispyles** [comment]
@SaiUCM please follow the debugging instructions [here](https://otter-grader.readthedocs.io/en/latest/debugging.html#gradescope-setup) and if you're unable to resolve the issue feel free to open a new discussion or reach out over slack.
