### ISSUE TITLE
Statistics on number of students failed/passed each test case

### ISSUE THREAD

**Issue by codingPie** [ucbds-infra/otter-grader#885]
I wonder if I can get statistics on the % of students failed/passed each test case and who did so. This can be helpful to pinpoint issues such as: misleading or unclear instructions, incorrect or insufficient test cases, inadequate teaching on certain topics. Currently, Gradescope gives statistics on overall grade but this is not very helpful for item analysis. Thanks!

**Comment by chrispyles** [comment]
Otter doesn't have this functionality built in; since every assignment is graded separately, there's no way for Otter to gather statistics about multiple submissions.

**Comment by codingPie** [comment]
@chrispyles Thank you for explaining!
