### ISSUE TITLE
Cannot have grader built on Gradescope

### ISSUE THREAD

**Issue by codingPie** [ucbds-infra/otter-grader#892]
I created 2 simple graders and uploaded them to Gradescope. One could not finish building after a whole day. Tried to reupload the zip file and still cannot get it to finish building. Another one throw building errors. Both of them have the following warning. Any help is appreciated.

║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     playwright install-deps                          ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libnss3\                         ║
║         libnspr4\                                    ║
║         libgbm1                                      ║
║                                                      ║
║ <3 Playwright Team  
 at validateDependenciesLinux (/root/miniforge3/envs/otter-env/lib/python3.12/site-packages/playwright/driver/package/lib/server/registry/dependencies.js:216:9)
    at async Registry._validateHostRequirements (/root/miniforge3/envs/otter-env/lib/python3.12/site-packages/playwright/driver/package/lib/server/registry/index.js:753:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/root/miniforge3/envs/otter-env/lib/python3.12/site-packages/playwright/driver/package/lib/server/registry/index.js:851:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/root/miniforge3/envs/otter-env/lib/python3.12/site-packages/playwright/driver/package/lib/server/registry/index.js:840:43)
    at async t.<anonymous> (/root/miniforge3/envs/otter-env/lib/python3.12/site-packages/playwright/driver/package/lib/cli/program.js:137:7)
The following arguments were not expected: --all init
Run with --help for more information.

The one that err out stoped right here. The build errors:
The command '/bin/sh -c bash /gradescope/setup.sh' returned a non-zero code: 109

**Comment by chrispyles** [comment]
Can you try adding the line `mamba run -n otter-env playwright install-deps` to the setup.sh file in the autograder zip file **right before** the line `mamba run -n otter-env playwright install chromium` and then rebuild the grading image with the new zip?

**Comment by codingPie** [comment]
Thank you! @chrispyles 

I did and still got a build error. Here is the new error:
FFMPEG playwright build v1010 downloaded to /root/.cache/ms-playwright/ffmpeg-1010
Downloading Chromium Headless Shell 131.0.6778.33 (playwright build v1148) from https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-linux.zip
|                                                                                |   0% of 100.9 MiB
|■■■■■■■■                                                                        |  10% of 100.9 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 100.9 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 100.9 MiB
Chromium Headless Shell 131.0.6778.33 (playwright build v1148) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1148
The following arguments were not expected: --all init

The command '/bin/sh -c bash /gradescope/setup.sh' returned a non-zero code: 109

I attached my setup.sh here as well
[setup.sh.zip](https://github.com/user-attachments/files/18140854/setup.sh.zip)

**Comment by codingPie** [comment]
@chrispyles Hi, I tried to build the failed grader today and all were successful. There seemed to be a long lasting server error over the weekend. Thank you for trying to help!

**Comment by chrispyles** [comment]
Glad to hear this is fixed.
