### ISSUE TITLE
Notebooks output by Google Colab don't work with otter assign

### ISSUE THREAD

**Issue by jcpeterson** [ucbds-infra/otter-grader#895]
Notebooks output by Google Colab don't work with otter assign

My current workaround is to manually edit the metadata of the colab-output notebook to include a single new line `"language": "python"` under `kernelspec`,

from:

```  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}```

to:

```  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3",
      "language": "python"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}```

**Comment by chrispyles** [comment]
According to the [jupyter notebook format spec](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernelspecs), this is not a valid kernelspec; I'm not sure why Colab isn't populating the `language` key. I can update Otter Assign to assume the language is Python if there is no `language`, but I don't want to engage in string parsing to attempt to determine the right language.
